/* ==========================================================================
   BOOK DATA — Carol's real collection, imported from the lit-huddle exports.

   Merged and deduplicated from three source files that overlapped heavily
   (lit_huddle_all_recovered_books.csv, lit_huddle_collection.csv,
   lit-huddle-library.csv): 254 raw rows collapsed to 225 unique owned/read
   books + 7 wishlist-only books (seeded separately — see wishlist-data.js).

   For each book:
   - `format` ("audiobook" | "physical") came from the source files' own
     Audible/book tags — 223 audiobooks, 2 physical in this collection.
   - `genres` and `mood` were inferred from each source's free-text
     genre/mood/shelf labels via keyword rules, so they're a best-effort
     read of what you'd already written down, not invented from scratch.
   - `cover`, `year`, `pages`, `publisher`, and `blurb` were fetched live
     from the Open Library API by title+author. `pages` drives each
     spine's width/height/binding in genBookStyle() (app.js) — without it
     every book defaulted to a uniform 300-page look, which is exactly
     what happened before this field was added.
   - `spine`/`band`/`ink` are real colors extracted from each book's cover
     art (same edge-average algorithm the original site uses), picking the
     cleanest-extracting of several candidate editions per book. Where no
     candidate extracted cleanly (busy/illustrated covers average into
     mud), a hand-picked, genre-themed fallback palette is used instead —
     see extract_spine_colors.py. 189/225 books here got real extracted
     colors; 36 use the curated fallback. A handful of obscure/regional or
     audio-only titles (radio dramas, Tamil-language titles, small audio
     collections) also have no cover indexed at all, so those fields are
     blank/null and fall back to sensible defaults.
   - `finished` is null for all of them — none of the source files had
     dates, so nothing was fabricated. The book modal shows "In the
     collection" instead of a fabricated date.
   - `reading`: true marks a book as currently in progress — it's pulled
     out of the main shelf and shown on its own "Currently acquainted
     with" shelf instead. None are marked this way by default; use a
     book's modal ("+ Mark as reading", owner-only) or the "+ Add a book"
     dialog's Status toggle to set one.

   Edit anything below directly, or use the site's own "+ Add a book" /
   "My thoughts" flows (owner sign-in required) to add and annotate books
   going forward — both write to the same shape as what's here.
   ========================================================================== */

window.LIBRARY_BOOKS = [
  {
    id: "the-beatrix-potter-collection-101",
    title: "The Beatrix Potter Collection",
    author: "Beatrix Potter",
    genres: ["Children's", "Classic Literature"],
    mood: ["Cozy", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10447931-L.jpg",
    year: 1900,
    pages: 55,
    blurb: "",
    rating: 0,
    spine: "#eed0a2",
    band: "#e05d41",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Grange Books",
  },
  {
    id: "paddington-192",
    title: "Paddington",
    author: "Michael Bond",
    genres: ["Children's", "Classic Literature"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/394112-L.jpg",
    year: 1960,
    pages: 144,
    blurb: "Mr. and Mrs. Brown first met Paddington, a most endearing bear from Darkest Peru on a railway platform in London. A sign hanging around his neck said, \"Please look after this bear. Thank you\" So that is just what they did. From the very first night when he attempted his first…",
    rating: 0,
    spine: "#4a5870",
    band: "#fc3700",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Editorii RAO",
  },
  {
    id: "the-charles-dickens-collection-25",
    title: "The Charles Dickens Collection",
    author: "Charles Dickens",
    genres: ["Classic Literature"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12875748-L.jpg",
    year: 1822,
    pages: 414,
    blurb: "Oliver Twist; or, The Parish Boy's Progress, is the second novel by English author Charles Dickens. It was originally published as a serial from 1837 to 1839, and as a three-volume book in 1838. The story follows the titular orphan, who, after being raised in a workhouse,…",
    rating: 0,
    spine: "#cacddc",
    band: "#d3d7ea",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "La Spiga-Meravigli",
  },
  {
    id: "to-kill-a-mockingbird-32",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genres: ["Classic Literature"],
    mood: ["Heartwarming", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12784310-L.jpg",
    year: 1960,
    pages: 320,
    blurb: "One of the best-loved stories of all time, To Kill a Mockingbird has been translated into more than 40 languages, sold more than 30 million copies worldwide, served as the basis for an enormously popular motion picture, and voted one of the best novels of the 20th century by…",
    rating: 0,
    spine: "#8f8f94",
    band: "#8f9298",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "FollettBound Platinum",
  },
  {
    id: "treasure-island-69",
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    genres: ["Classic Literature"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/robert-louis-stevenson/treasure-island/downloads/cover.jpg",
    year: 1880,
    pages: 248,
    blurb: "",
    rating: 0,
    spine: "#968b91",
    band: "#ee984d",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Barnes & Noble Press",
  },
  {
    id: "classics-of-american-literature-79",
    title: "Classics of American Literature",
    author: "Arnold Weinstein",
    genres: ["Classic Literature"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "covers/generated/classics-of-american-literature-79.jpg",
    year: 1998,
    pages: 84,
    blurb: "",
    rating: 0,
    spine: "#3a0f10",
    band: "#e8c468",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "The Teaching Company",
  },
  {
    id: "wuthering-heights-141",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    genres: ["Classic Literature"],
    mood: ["Dark & Moody", "Thought-provoking", "Suspenseful"],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/emily-bronte/wuthering-heights/downloads/cover.jpg",
    year: 1846,
    pages: 318,
    blurb: "Wuthering Heights is an 1847 novel by Emily Brontë, initially published under the pseudonym Ellis Bell. It concerns two families of the landed gentry living on the West Yorkshire moors, the Earnshaws and the Lintons, and their turbulent relationships with Earnshaw's adopted son,…",
    rating: 0,
    spine: "#4e5340",
    band: "#a87b56",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Xist Publishing",
  },
  {
    id: "david-copperfield-87",
    title: "David Copperfield",
    author: "Charles Dickens",
    genres: ["Classic Literature"],
    mood: ["Cozy", "Thought-provoking", "Bittersweet"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9279255-L.jpg",
    year: 1800,
    pages: 742,
    blurb: "",
    rating: 0,
    spine: "#372b25",
    band: "#ac895c",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Edicions Proa",
  },
  {
    id: "the-ultimate-classics-collection-volume--91",
    title: "The Ultimate Classics Collection – Volume One",
    author: "Various Classic Authors",
    genres: ["Classic Literature"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "covers/generated/the-ultimate-classics-collection-volume--91.jpg",
    year: 1200,
    pages: 1462,
    blurb: "The purpose of The Original African Heritage Study Bible is to interpret the Bible as it relates specifically to persons of African descent and thereby to foster an appreciation of the multiculturalism inherent in the Bible. The Original African Heritage Study Bible offers a…",
    rating: 0,
    spine: "#3a0f10",
    band: "#e8c468",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Wm. Andrus",
  },
  {
    id: "the-wind-in-the-willows-131",
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    genres: ["Classic Literature"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/14920876-L.jpg",
    year: 1908,
    pages: 192,
    blurb: "The adventures of four amiable animals, Rat, Toad, Mole and Badger, along a river in the English countryside.",
    rating: 0,
    spine: "#707c3d",
    band: "#1094ac",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Penguin UK",
  },
  {
    id: "the-secret-garden-142",
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    genres: ["Classic Literature"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12622062-L.jpg",
    year: 1911,
    pages: 256,
    blurb: "",
    rating: 0,
    spine: "#757c5b",
    band: "#e2c02a",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Penguin USA, Inc.",
  },
  {
    id: "the-anne-of-green-gables-collection-171",
    title: "The Anne of Green Gables Collection",
    author: "L. M. Montgomery",
    genres: ["Classic Literature"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14641084-L.jpg",
    year: 1908,
    pages: 309,
    blurb: "Anne, an eleven-year-old orphan, is sent by mistake to live with a lonely, middle-aged brother and sister on a Prince Edward Island farm and proceeds to make an indelible impression on everyone around her.",
    rating: 0,
    spine: "#535941",
    band: "#915f29",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Penguin Books Ltd.",
  },
  {
    id: "animal-farm-180",
    title: "Animal Farm",
    author: "George Orwell",
    genres: ["Classic Literature"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/11261770-L.jpg",
    year: 1945,
    pages: 128,
    blurb: "Animal Farm is a brilliant political satire and a powerful and affecting story of revolutions and idealism, power and corruption. 'All animals are equal. But some animals are more equal than others.' Mr Jones of Manor Farm is so lazy and drunken that one day he forgets to feed…",
    rating: 0,
    spine: "#050505",
    band: "#9a2109",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Companion Library",
  },
  {
    id: "the-enchanted-april-7",
    title: "The Enchanted April",
    author: "Elizabeth von Arnim",
    genres: ["Classic Literature", "Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/872835-L.jpg",
    year: 1922,
    pages: 223,
    blurb: "\"A notice in The Times addressed to 'Those Who Appreciate Wistaria and Sunshine' advertises a 'small medieval Italian Castle to be let for the month of April'. Four very different women take up the offer: Mrs Wilkins and Mrs Arbuthnot, both fleeing unappreciative husbands;…",
    rating: 0,
    spine: "#551d3c",
    band: "#c49545",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Silhouette",
  },
  {
    id: "to-the-lighthouse-60",
    title: "To the Lighthouse",
    author: "Virginia Woolf",
    genres: ["Classic Literature", "Fiction"],
    mood: ["Thought-provoking", "Slow & Contemplative", "Suspenseful"],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/virginia-woolf/to-the-lighthouse/downloads/cover.jpg",
    year: 1927,
    pages: 242,
    blurb: "This novel is an extraordinarily poignant evocation of a lost happiness that lives on in the memory. For years now the Ramsays have spent every summer in their holiday home in Scotland, and they expect these summers will go on forever.In this, her most autobiographical novel,…",
    rating: 0,
    spine: "#1c2b4a",
    band: "#c9a44c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Norton & Company Limited, W. W.",
  },
  {
    id: "normal-people-61",
    title: "Normal People",
    author: "Sally Rooney",
    genres: ["Classic Literature", "Fiction"],
    mood: ["Bittersweet"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8794265-L.jpg",
    year: 2018,
    pages: 304,
    blurb: "At school Connell and Marianne pretend not to know each other. He’s popular and well-adjusted, star of the school soccer team while she is lonely, proud, and intensely private. But when Connell comes to pick his mother up from her housekeeping job at Marianne’s house, a strange…",
    rating: 0,
    spine: "#7aa487",
    band: "#7ab139",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Knopf Canada",
  },
  {
    id: "the-dutch-house-188",
    title: "The Dutch House",
    author: "Ann Patchett",
    genres: ["Classic Literature", "Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8788823-L.jpg",
    year: 2019,
    pages: 352,
    blurb: "A HOUSE FORMERLY OWNED BY A WEALTHY COUPLE IS PASSED DOWN TO A NEWLY RICH BUSINESSMAN AND HIS CHILDREN. HOW THE HOUSE OWNERSHIP MOVES THROUGH TIME.",
    rating: 0,
    spine: "#5c1f2e",
    band: "#c9a44c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "HarperCollinsPublishers",
  },
  {
    id: "war-and-peace-0",
    title: "War and Peace",
    author: "Leo Tolstoy",
    genres: ["Classic Literature", "Historical Fiction"],
    mood: ["Adventurous", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15111564-L.jpg",
    year: 1845,
    pages: 696,
    blurb: "War and Peace delineates in graphic detail events surrounding the French invasion of Russia, and the impact of the Napoleonic era on Tsarist society, as seen through the eyes of five Russian aristocratic families. The novel begins in the year 1805 during the reign of Tsar…",
    rating: 0,
    spine: "#8f5444",
    band: "#cc4128",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Hachette et cie.",
  },
  {
    id: "the-crossing-128",
    title: "The Crossing",
    author: "Andrew Miller",
    genres: ["Classic Literature", "Historical Fiction"],
    mood: [],
    format: "audiobook",
    cover: "covers/generated/the-crossing-128.jpg",
    year: 2015,
    pages: 321,
    blurb: "\"Who else has entered Tim's life the way Maud did? This girl who fell past him, lay seemingly dead on the ground, then stood and walked. That was where it all began. He wants her--wants to rescue her, to reach her. Yet there is nothing to suggest Maud has any need of him, that…",
    rating: 0,
    spine: "#3a0f10",
    band: "#e8c468",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Sceptre",
  },
  {
    id: "a-bit-of-fry-laurie-47",
    title: "A Bit of Fry & Laurie",
    author: "Stephen Fry; Hugh Laurie",
    genres: ["Comedy"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9802089-L.jpg",
    year: 2014,
    pages: 388,
    blurb: "\"By his early thirties, Stephen Fry--writer, comedian, star of stage and screen--had, as they say, \"made it.\" Much loved on British television, author of a critically acclaimed and bestselling first novel, with a glamorous and glittering cast of friends, he had more work than…",
    rating: 0,
    spine: "#5d403a",
    band: "#922c16",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "WF Howes Ltd",
  },
  {
    id: "yes-minister-yes-prime-minister-77",
    title: "Yes Minister & Yes Prime Minister",
    author: "Antony Jay; Jonathan Lynn",
    genres: ["Comedy"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6799293-L.jpg",
    year: 1989,
    pages: 256,
    blurb: "",
    rating: 0,
    spine: "#1f120b",
    band: "#c21009",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Ebury Publishing",
  },
  {
    id: "jeeves-collection-175",
    title: "Jeeves Collection",
    author: "P. G. Wodehouse",
    genres: ["Comedy"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/1284780-L.jpg",
    year: 1931,
    pages: 224,
    blurb: "",
    rating: 0,
    spine: "#858045",
    band: "#e18d0c",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Overlook Press",
  },
  {
    id: "the-hitchhiker-s-guide-to-the-galaxy-205",
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    genres: ["Comedy"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12986869-L.jpg",
    year: 1979,
    pages: 216,
    blurb: "The Hitchhiker's Guide to the Galaxy is the first of six books in the Hitchhiker's Guide to the Galaxy comedy science fiction \"hexalogy\" by Douglas Adams. The novel is an adaptation of the first four parts of Adams's radio series of the same name. The novel was first published…",
    rating: 0,
    spine: "#324f57",
    band: "#1ba4bf",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Harmony Books",
  },
  {
    id: "just-william-211",
    title: "Just William",
    author: "Richmal Crompton",
    genres: ["Comedy"],
    mood: [],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/richmal-crompton/just-william/downloads/cover.jpg",
    year: 1922,
    pages: 218,
    blurb: "There is only one Just William. The loveable imp has been harassing his unfortunate family and delighting hundreds of thousands of readers for years. Here, the Outlaws plan a day of non-stop adventure. The only problem is, William is meant to be babysitting. But William won't…",
    rating: 0,
    spine: "#120b07",
    band: "#dda17a",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Collins",
  },
  {
    id: "three-men-in-a-boat-218",
    title: "Three Men in a Boat",
    author: "Jerome K. Jerome",
    genres: ["Comedy"],
    mood: [],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/jerome-k-jerome/three-men-in-a-boat/downloads/cover.jpg",
    year: 1889,
    pages: 184,
    blurb: "",
    rating: 0,
    spine: "#6e8a98",
    band: "#d46b2e",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Time-Life Books",
  },
  {
    id: "a-bear-called-paddington-53",
    title: "A Bear Called Paddington",
    author: "Michael Bond",
    genres: ["Comedy", "Children's"],
    mood: ["Cozy", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6381303-L.jpg",
    year: 1960,
    pages: 144,
    blurb: "Mr. and Mrs. Brown first met Paddington, a most endearing bear from Darkest Peru on a railway platform in London. A sign hanging around his neck said, \"Please look after this bear. Thank you\" So that is just what they did. From the very first night when he attempted his first…",
    rating: 0,
    spine: "#88956d",
    band: "#da0d29",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Editorii RAO",
  },
  {
    id: "paddington-at-work-118",
    title: "Paddington at Work",
    author: "Michael Bond",
    genres: ["Comedy", "Children's"],
    mood: ["Cozy", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/394112-L.jpg",
    year: 1966,
    pages: 128,
    blurb: "Paddington returns from Peru and tries his hand at such things as the stock market, barbering, and even ballet; but he decides he would rather be his bear self.",
    rating: 0,
    spine: "#4a5870",
    band: "#fc3700",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Harpercollins",
  },
  {
    id: "vanity-fair-1",
    title: "Vanity Fair",
    author: "William Makepeace Thackeray",
    genres: ["Comedy", "Classic Literature"],
    mood: ["Adventurous", "Whimsical"],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/william-makepeace-thackeray/vanity-fair/downloads/cover.jpg",
    year: 1800,
    pages: 699,
    blurb: "No one is better equipped in the struggle for wealth and worldly success than the alluring and ruthless Becky Sharp, who defies her impoverished background to clamber up the class ladder. Her sentimental companion Amelia, however, longs only for caddish soldier George. As the…",
    rating: 0,
    spine: "#87664b",
    band: "#eb814d",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "University of Cambridge ESOL Examinations",
  },
  {
    id: "don-quixote-48",
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    genres: ["Comedy", "Classic Literature"],
    mood: ["Adventurous", "Whimsical"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/miguel-de-cervantes-saavedra/don-quixote/john-ormsby/downloads/cover.jpg",
    year: 1600,
    pages: 519,
    blurb: "*Don Quijote de la Mancha* es una novela escrita por el español Miguel de Cervantes Saavedra. Publicada su primera parte con el título de *El ingenioso hidalgo don Quijote de la Mancha* a comienzos de 1605, es la obra más destacada de la literatura española y una de las…",
    rating: 0,
    spine: "#614a2c",
    band: "#dfb461",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Collectible First Editions",
  },
  {
    id: "a-confederacy-of-dunces-129",
    title: "A Confederacy of Dunces",
    author: "John Kennedy Toole",
    genres: ["Comedy", "Classic Literature"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/2195715-L.jpg",
    year: 1980,
    pages: 391,
    blurb: "A Confederacy of Dunces is an American comic masterpiece. John Kennedy Toole's hero is one Ignatius J. Reilly, \"huge, obese, fractious, fastidious, a latter-day Gargantua, a Don Quixote of the French Quarter. His story bursts with wholly original characters, denizens of New…",
    rating: 0,
    spine: "#e6e7e6",
    band: "#d2c927",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "LSU Press",
  },
  {
    id: "all-things-bright-and-beautiful-40",
    title: "All Things Bright and Beautiful",
    author: "James Herriot",
    genres: ["Comedy", "Nonfiction"],
    mood: ["Cozy", "Slow & Contemplative"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9904960-L.jpg",
    year: 1974,
    pages: 384,
    blurb: "This beloved sequel to Herriot's first collection, “All Creatures Great and Small”, picks up as Herriot, now newly married, journeys among the remote hillside farms and valley towns of the Yorkshire Dales, caring for their inhabitants—both two- and four-legged. Throughout,…",
    rating: 0,
    spine: "#cbd0ad",
    band: "#cb7521",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Book Club Associates",
  },
  {
    id: "the-night-circus-29",
    title: "The Night Circus",
    author: "Erin Morgenstern",
    genres: ["Fantasy"],
    mood: ["Cozy", "Suspenseful"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8773134-L.jpg",
    year: 2011,
    pages: 512,
    blurb: "The circus arrives without warning. No announcements precede it. It is simply there, when yesterday it was not. Within the black-and-white striped canvas tents is an utterly unique experience full of breathtaking amazements. It is called Le Cirque des Rêves, and it is only open…",
    rating: 0,
    spine: "#121011",
    band: "#de3f27",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Columna",
  },
  {
    id: "from-the-wizarding-archive-113",
    title: "From the Wizarding Archive",
    author: "J. K. Rowling",
    genres: ["Fantasy"],
    mood: ["Adventurous", "Nostalgic"],
    format: "audiobook",
    cover: "covers/generated/from-the-wizarding-archive-113.jpg",
    year: null,
    pages: 272,
    blurb: "",
    rating: 0,
    spine: "#0f2e1a",
    band: "#e8c468",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "the-tales-of-beedle-the-bard-144",
    title: "The Tales of Beedle the Bard",
    author: "J. K. Rowling",
    genres: ["Fantasy"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13776199-L.jpg",
    year: 2008,
    pages: 127,
    blurb: "A collection fairy tales for young wizards and witches, with each story followed by observations on Wizarding history, personal reminiscences, and information on the story's key elements by Hogwarts headmaster, Albus Dumbledore. Wizard and the Hopping Pot -- Fountain of Fair…",
    rating: 0,
    spine: "#121926",
    band: "#ff7955",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "salamandra",
  },
  {
    id: "the-hobbit-170",
    title: "The Hobbit",
    author: "J. R. R. Tolkien",
    genres: ["Fantasy"],
    mood: ["Adventurous", "Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8406766-L.jpg",
    year: 1937,
    pages: 310,
    blurb: "The Hobbit is a tale of high adventure, undertaken by a company of dwarves in search of dragon-guarded gold. A reluctant partner in this perilous quest is Bilbo Baggins, a comfort-loving unambitious hobbit, who surprises even himself by his resourcefulness and skill as a…",
    rating: 0,
    spine: "#698965",
    band: "#fbdd01",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Houghton Mifflin, 1966",
  },
  {
    id: "the-happy-prince-other-tales-80",
    title: "The Happy Prince & Other Tales",
    author: "Oscar Wilde",
    genres: ["Fantasy", "Classic Literature"],
    mood: ["Heartwarming", "Whimsical", "Bittersweet"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9205142-L.jpg",
    year: 1888,
    pages: 50,
    blurb: "THE HAPPY PRINCE AND OTHER TALES is a collection of fables - THE HAPPY PRINCE had been, in life, a joyful personality. However, now, immortalised by a gold and jewel encrusted statue, he's saddened by the poverty of his citizens. Unable to move, he enlists the help of a swallow…",
    rating: 0,
    spine: "#fdfdfd",
    band: "#d8d8d8",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "David Nutt",
  },
  {
    id: "italo-calvino-a-bbc-radio-collection-130",
    title: "Italo Calvino: A BBC Radio Collection",
    author: "Italo Calvino",
    genres: ["Fantasy", "Classic Literature"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "covers/generated/italo-calvino-a-bbc-radio-collection-130.jpg",
    year: null,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#0f2e1a",
    band: "#e8c468",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "peter-pan-174",
    title: "Peter Pan",
    author: "J. M. Barrie",
    genres: ["Fantasy", "Classic Literature"],
    mood: ["Adventurous", "Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8237052-L.jpg",
    year: 1911,
    pages: 183,
    blurb: "The adventures of the three Darling children in Never-Never Land with Peter Pan, the boy who would not grow up. ---------- ###German-language description: Peter Pan, das ist der Junge, der nie erwachsen wird und auf einer Insel lebt, auf der alles möglich st. Wendy und ihre…",
    rating: 0,
    spine: "#907c22",
    band: "#a88e1f",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Kidsbooks",
  },
  {
    id: "nanny-mcphee-and-the-big-bang-9",
    title: "Nanny McPhee and The Big Bang",
    author: "Emma Thompson",
    genres: ["Fantasy", "Comedy"],
    mood: ["Cozy", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6452822-L.jpg",
    year: 2010,
    pages: 304,
    blurb: "Brilliant stand-alone novel to tie in with the release of the new Nanny McPhee film in Spring 2010 Both screenplay and novel written by Emma Thompson Nanny McPhee embarks on a brand new adventure in this brilliant, funny and captivating novel based on the new Nanny McPhee film.…",
    rating: 0,
    spine: "#1f4a3a",
    band: "#c9a44c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Bloomsbury Publishing",
  },
  {
    id: "nelson-mandela-s-favorite-african-folkta-168",
    title: "Nelson Mandela's Favorite African Folktales",
    author: "Various",
    genres: ["Fantasy", "Mythology"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/251328-L.jpg",
    year: 2007,
    pages: 144,
    blurb: "",
    rating: 0,
    spine: "#b49538",
    band: "#ffba0b",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "W. W. Norton",
  },
  {
    id: "penguin-sleep-tales-66",
    title: "Penguin Sleep Tales",
    author: "Penguin",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6459276-L.jpg",
    year: 1800,
    pages: 388,
    blurb: "A Tale of Two Cities is a historical novel published in 1859 by Charles Dickens, set in London and Paris before and during the French Revolution. The novel tells the story of the French Doctor Manette, his 18-year-long imprisonment in the Bastille in Paris, and his release to…",
    rating: 0,
    spine: "#ffffff",
    band: "#f96e04",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Black Cat",
  },
  {
    id: "remarkably-bright-creatures-109",
    title: "Remarkably Bright Creatures",
    author: "Shelby Van Pelt",
    genres: ["Fiction"],
    mood: ["Cozy", "Bittersweet"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12019989-L.jpg",
    year: 2022,
    pages: 368,
    blurb: "After Tova Sullivan's husband died, she began working the night cleaner shift at the Sowell Bay Aquarium. Ever since her eighteen-year-old son, Erik, mysteriously vanished on a boat over thirty years ago keeping busy has helped her cope. One night she meets Marcellus, a giant…",
    rating: 0,
    spine: "#ed1c22",
    band: "#ef000a",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "HarperLuxe",
  },
  {
    id: "the-boy-the-mole-the-fox-and-the-horse-154",
    title: "The Boy, the Mole, the Fox and the Horse",
    author: "Charlie Mackesy",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "covers/generated/the-boy-the-mole-the-fox-and-the-horse-154.jpg",
    year: 2019,
    pages: 128,
    blurb: "",
    rating: 0,
    spine: "#0f2a3a",
    band: "#e0c468",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Beijing United Publishing co., LTD",
  },
  {
    id: "the-natural-navigator-156",
    title: "The Natural Navigator",
    author: "Tristan Gooley",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10326883-L.jpg",
    year: 2010,
    pages: 304,
    blurb: "Offers a guide to the age-old tradition of navigation on both land and sea through the observation of the Sun, Moon, and stars, weather patterns, landscape, growth of plants, and habitats of wildlife.",
    rating: 0,
    spine: "#860e17",
    band: "#832927",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Experiment",
  },
  {
    id: "the-midnight-library-157",
    title: "The Midnight Library",
    author: "Matt Haig",
    genres: ["Fiction"],
    mood: ["Thought-provoking", "Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10313767-L.jpg",
    year: 2020,
    pages: 304,
    blurb: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices . . . Would you have done anything different, if you had…",
    rating: 0,
    spine: "#19233c",
    band: "#ff8234",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Bertrand Brasil",
  },
  {
    id: "alice-s-adventures-in-wonderland-196",
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/lewis-carroll/alices-adventures-in-wonderland/john-tenniel/downloads/cover.jpg",
    year: 1865,
    pages: 133,
    blurb: "Alice's Adventures in Wonderland (commonly Alice in Wonderland) is an 1865 English children's novel by Lewis Carroll. A young girl named Alice falls through a rabbit hole into a fantasy world of anthropomorphic creatures. It is seen as an example of the literary nonsense genre.…",
    rating: 0,
    spine: "#564935",
    band: "#c46734",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Zen Wen Shu Ju",
  },
  {
    id: "anne-of-green-gables-197",
    title: "Anne of Green Gables",
    author: "L. M. Montgomery",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14641084-L.jpg",
    year: 1908,
    pages: 309,
    blurb: "",
    rating: 0,
    spine: "#535941",
    band: "#915f29",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Penguin Books Ltd.",
  },
  {
    id: "cranford-201",
    title: "Cranford",
    author: "Elizabeth Gaskell",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/elizabeth-gaskell/cranford/downloads/cover.jpg",
    year: 1853,
    pages: 244,
    blurb: "Cranford was first serialized in Charles Dickens’ magazine Household Words between 1851 and 1853. The structureless nature of the stories, and the fact that <a…",
    rating: 0,
    spine: "#7c6e55",
    band: "#ecaa59",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "ReadHowYouWant.com",
  },
  {
    id: "the-age-of-innocence-214",
    title: "The Age of Innocence",
    author: "Edith Wharton",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13133998-L.jpg",
    year: 1920,
    pages: 348,
    blurb: "Edith Wharton's most famous novel, written immediately after the end of the First World War, is a brilliantly realized anatomy of New York society in the 1870s, the world in which she grew up, and from which she spent her life escaping. Newland Archer, Wharton's protagonist,…",
    rating: 0,
    spine: "#936765",
    band: "#c44150",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Appleton",
  },
  {
    id: "the-time-machine-216",
    title: "The Time Machine",
    author: "H. G. Wells",
    genres: ["Fiction"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6569999-L.jpg",
    year: 1895,
    pages: 120,
    blurb: "The Time Traveller, a dreamer obsessed with traveling through time, builds himself a time machine and, much to his surprise, travels over 800,000 years into the future. He lands in the year 802701: the world has been transformed by a society living in apparent harmony and bliss,…",
    rating: 0,
    spine: "#040717",
    band: "#2d7eb0",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Yoyo USA",
  },
  {
    id: "the-wonderful-wizard-of-oz-217",
    title: "The Wonderful Wizard of Oz",
    author: "L. Frank Baum",
    genres: ["Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/552443-L.jpg",
    year: 1899,
    pages: 159,
    blurb: "Over a century after its initial publication, The Wonderful Wizard of Oz is still captivating the hearts of countless readers. Come adventure with Dorothy and her three friends: the Scarecrow, the Tin Woodman, and the Cowardly Lion, as they follow the Yellow Brick Road to the…",
    rating: 0,
    spine: "#46903c",
    band: "#ffce08",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Bobbs-Merrill",
  },
  {
    id: "through-the-looking-glass-219",
    title: "Through the Looking-Glass",
    author: "Lewis Carroll",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/lewis-carroll/through-the-looking-glass/john-tenniel/downloads/cover.jpg",
    year: 1865,
    pages: 134,
    blurb: "",
    rating: 0,
    spine: "#372b23",
    band: "#a39d3f",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Saalfield Pub. Co.",
  },
  {
    id: "winter-holiday-223",
    title: "Winter Holiday",
    author: "Arthur Ransome",
    genres: ["Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/674595-L.jpg",
    year: 1933,
    pages: 352,
    blurb: "This may be the best book in the Swallows and Amazons series, which means that it might be the best children's book ever written. The Swallows and Amazons are exploring the Arctic (the area around the lake) during winter vacation when they meet Dick and Dorothea Callum, staying…",
    rating: 0,
    spine: "#f8f8d8",
    band: "#32a698",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Penguin Random House",
  },
  {
    id: "we-have-always-lived-in-the-castle-133",
    title: "We Have Always Lived in the Castle",
    author: "Shirley Jackson",
    genres: ["Gothic"],
    mood: ["Dark & Moody", "Suspenseful"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/11545332-L.jpg",
    year: 1962,
    pages: 187,
    blurb: "Shirley Jackson's beloved gothic tale of a peculiar girl named Merricat and her family's dark secret Taking readers deep into a labyrinth of dark neurosis, We Have Always Lived in the Castle is a deliciously unsettling novel about a perverse, isolated, and possibly murderous…",
    rating: 0,
    spine: "#2d2e31",
    band: "#bfd2ec",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Pocket",
  },
  {
    id: "the-haunting-of-hill-house-134",
    title: "The Haunting of Hill House",
    author: "Shirley Jackson",
    genres: ["Gothic"],
    mood: ["Dark & Moody"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15221954-L.jpg",
    year: 1959,
    pages: 246,
    blurb: "First published in 1959, Shirley Jackson's The Haunting of Hill House has been hailed as a perfect work of unnerving terror. It is the story of four seekers who arrive at a notoriously unfriendly pile called Hill House: Dr. Montague, an occult scholar looking for solid evidence…",
    rating: 0,
    spine: "#22323f",
    band: "#ff0200",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Adelphi eBook",
  },
  {
    id: "frankenstein-202",
    title: "Frankenstein",
    author: "Mary Shelley",
    genres: ["Gothic"],
    mood: ["Dark & Moody"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/2331229-L.jpg",
    year: 1818,
    pages: 240,
    blurb: "",
    rating: 0,
    spine: "#acaaac",
    band: "#a65e72",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Bobbs-Merrill",
  },
  {
    id: "jane-eyre-208",
    title: "Jane Eyre",
    author: "Charlotte Bronte",
    genres: ["Gothic"],
    mood: ["Dark & Moody"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/charlotte-bronte/jane-eyre/downloads/cover.jpg",
    year: 1847,
    pages: 480,
    blurb: "The novel is set somewhere in the north of England. Jane's childhood at Gateshead Hall, where she is emotionally and physically abused by her aunt and cousins; her education at Lowood School, where she acquires friends and role models but also suffers privations and oppression;…",
    rating: 0,
    spine: "#2f3226",
    band: "#926b4c",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Globe Fearon",
  },
  {
    id: "the-strange-case-of-dr-jekyll-and-mr-hyd-209",
    title: "The Strange Case of Dr Jekyll and Mr Hyde",
    author: "Robert Louis Stevenson",
    genres: ["Gothic"],
    mood: ["Dark & Moody"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/11360069-L.jpg",
    year: 1875,
    pages: 130,
    blurb: "Mr. Gabriel Utterson is a serious, austere lawyer living a humdrum life in Victorian London. Yet there is a strange clause in his friend, Dr. Henry Jekyll's will: should he disappear for more than 3 months, everything will be inherited by Hyde. But after Edward Hyde's darker…",
    rating: 0,
    spine: "#060606",
    band: "#dc9463",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "TOR",
  },
  {
    id: "the-picture-of-dorian-gray-51",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genres: ["Gothic", "Classic Literature"],
    mood: ["Dark & Moody", "Suspenseful"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6816209-L.jpg",
    year: 1890,
    pages: 246,
    blurb: "**The Picture of Dorian Gray** is a philosophical novel by Irish writer Oscar Wilde. A shorter novella-length version was published in the July 1890 issue of the American periodical *Lippincott’s Monthly Magazine*. The novel-length version was published in April 1891. (Source:…",
    rating: 0,
    spine: "#0b0b09",
    band: "#97392d",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Norton & Company Limited, W. W.",
  },
  {
    id: "the-canterville-ghost-147",
    title: "The Canterville Ghost",
    author: "Oscar Wilde",
    genres: ["Gothic", "Comedy"],
    mood: ["Dark & Moody", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10201103-L.jpg",
    year: 1887,
    pages: 93,
    blurb: "",
    rating: 0,
    spine: "#5e6260",
    band: "#d3ce28",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Independently published",
  },
  {
    id: "the-ultimate-horror-collection-82",
    title: "The Ultimate Horror Collection",
    author: "Various",
    genres: ["Gothic", "Horror"],
    mood: ["Dark & Moody", "Suspenseful"],
    format: "audiobook",
    cover: "covers/generated/the-ultimate-horror-collection-82.jpg",
    year: 1818,
    pages: 240,
    blurb: "",
    rating: 0,
    spine: "#1a1a1a",
    band: "#d4af37",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Bobbs-Merrill",
  },
  {
    id: "dracula-182",
    title: "Dracula",
    author: "Bram Stoker",
    genres: ["Gothic", "Horror"],
    mood: ["Dark & Moody"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/1738960-L.jpg",
    year: 1897,
    pages: 384,
    blurb: "Na história, um casal e seus amigos são atormentados por Conde Drácula, uma entidade sobrenatural e hematófoga que, presa em uma maldição contagiosa, pretende se mudar de seu recluso castelo na Transilvânia para a efervescente Londres do século XIX. Com a ajuda do professor Van…",
    rating: 0,
    spine: "#982e33",
    band: "#99232b",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Grapevine India",
  },
  {
    id: "the-oscar-wilde-collection-81",
    title: "The Oscar Wilde Collection",
    author: "Oscar Wilde",
    genres: ["Gothic", "Poetry & Drama"],
    mood: ["Dark & Moody", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12837343-L.jpg",
    year: 1890,
    pages: 246,
    blurb: "",
    rating: 0,
    spine: "#efeee7",
    band: "#cdc6b8",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Norton & Company Limited, W. W.",
  },
  {
    id: "the-count-of-monte-cristo-19",
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    genres: ["Historical Fiction"],
    mood: ["Adventurous", "Fast-paced"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14937760-L.jpg",
    year: 1830,
    pages: 593,
    blurb: "",
    rating: 0,
    spine: "#535351",
    band: "#be2014",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Navbhardt",
  },
  {
    id: "sherlock-holmes-176",
    title: "Sherlock Holmes",
    author: "Arthur Conan Doyle",
    genres: ["Mystery & Thriller", "Classic Literature"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6717853-L.jpg",
    year: 1892,
    pages: 308,
    blurb: "The Adventures of Sherlock Holmes is a collection of twelve short stories by Arthur Conan Doyle, first published on 14 October 1892. It contains the earliest short stories featuring the consulting detective Sherlock Holmes, which had been published in twelve monthly issues of…",
    rating: 0,
    spine: "#1f465e",
    band: "#2a6d99",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Baker Street Press",
  },
  {
    id: "the-thursday-murder-club-125",
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    genres: ["Mystery & Thriller", "Comedy"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10201431-L.jpg",
    year: 2020,
    pages: 382,
    blurb: "In a peaceful retirement village, four unlikely friends meet weekly in the Jigsaw Room to discuss unsolved crimes; together they call themselves The Thursday Murder Club. When a local developer is found dead with a mysterious photograph left next to the body, the Thursday Murder…",
    rating: 0,
    spine: "#dc4e49",
    band: "#da3228",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Penguin Books",
  },
  {
    id: "rebecca-178",
    title: "Rebecca",
    author: "Daphne du Maurier",
    genres: ["Mystery & Thriller", "Gothic"],
    mood: ["Dark & Moody", "Suspenseful"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8238729-L.jpg",
    year: 1938,
    pages: 386,
    blurb: "With these words, the reader is ushered into an isolated gray stone mansion on the windswept Cornish coast, as the second Mrs. Maxim de Winter recalls the chilling events that transpired as she began her new life as the young bride of a husband she barely knew. For in every…",
    rating: 0,
    spine: "#2c1b1c",
    band: "#c93b23",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "The Literary Guild of America",
  },
  {
    id: "poirot-s-finest-cases-33",
    title: "Poirot's Finest Cases",
    author: "Agatha Christie",
    genres: ["Mystery & Thriller", "Poetry & Drama"],
    mood: ["Fast-paced", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7578641-L.jpg",
    year: 2013,
    pages: 1,
    blurb: "",
    rating: 0,
    spine: "#0e2222",
    band: "#04c1e3",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "AudioGO Limited",
  },
  {
    id: "more-of-poirot-s-finest-cases-34",
    title: "More of Poirot's Finest Cases",
    author: "Agatha Christie",
    genres: ["Mystery & Thriller", "Poetry & Drama"],
    mood: ["Adventurous", "Fast-paced", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7578641-L.jpg",
    year: null,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#0e2222",
    band: "#04c1e3",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "george-cragge-in-the-red-other-mysteries-72",
    title: "George Cragge: In the Red & Other Mysteries",
    author: "Mark Tavener",
    genres: ["Mystery & Thriller", "Poetry & Drama"],
    mood: ["Fast-paced", "Whimsical"],
    format: "audiobook",
    cover: "covers/generated/george-cragge-in-the-red-other-mysteries-72.jpg",
    year: null,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#14100f",
    band: "#d4a83c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "lord-peter-wimsey-bbc-radio-drama-collec-76",
    title: "Lord Peter Wimsey: BBC Radio Drama Collection Volume 1",
    author: "Dorothy L. Sayers",
    genres: ["Mystery & Thriller", "Poetry & Drama"],
    mood: ["Suspenseful", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8311819-L.jpg",
    year: 2018,
    pages: 1,
    blurb: "",
    rating: 0,
    spine: "#423d30",
    band: "#9e4000",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "BBC Books",
  },
  {
    id: "the-mysteries-of-udolpho-86",
    title: "The Mysteries of Udolpho",
    author: "Ann Radcliffe",
    genres: ["Mystery & Thriller", "Romance"],
    mood: ["Adventurous", "Dark & Moody", "Suspenseful"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15022787-L.jpg",
    year: 1794,
    pages: 506,
    blurb: "The Mysteries of Udolpho (1794) is the archetypal Gothic novel. A young woman, Emily St. Aubert, suffers the death of her father, followed by worsening physical and psychological death, mirrored in a landscape of crumbling castles and emotive Alps.",
    rating: 0,
    spine: "#1b675c",
    band: "#18886f",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "IndyPublish.com",
  },
  {
    id: "shyam-an-illustrated-retelling-of-the-bh-94",
    title: "Shyam: An Illustrated Retelling of the Bhagavata",
    author: "Devdutt Pattanaik",
    genres: ["Mythology"],
    mood: ["Thought-provoking"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8595197-L.jpg",
    year: 2018,
    pages: 304,
    blurb: "",
    rating: 0,
    spine: "#d93881",
    band: "#d50b79",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Penguin Books",
  },
  {
    id: "a-thousand-ships-158",
    title: "A Thousand Ships",
    author: "Natalie Haynes",
    genres: ["Mythology"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10294341-L.jpg",
    year: 2019,
    pages: 368,
    blurb: "",
    rating: 0,
    spine: "#163543",
    band: "#cbda01",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Mantle",
  },
  {
    id: "the-song-of-achilles-177",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    genres: ["Mythology"],
    mood: ["Bittersweet"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/7098465-L.jpg",
    year: 2011,
    pages: 386,
    blurb: "This is the story of the seige of Troy from the perspective of Achilles best-friend Patroclus. Although Patroclus is outcast from his home for disappointing his father he manages to be the only mortal who can keep up with the half-God Archilles. Even though many will know the…",
    rating: 0,
    spine: "#3a4a6e",
    band: "#c9a44c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Belog",
  },
  {
    id: "circe-199",
    title: "Circe",
    author: "Madeline Miller",
    genres: ["Mythology"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8739376-L.jpg",
    year: 2018,
    pages: 404,
    blurb: "",
    rating: 0,
    spine: "#5c401d",
    band: "#ffb818",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Thorndike Press Large Print",
  },
  {
    id: "heroes-203",
    title: "Heroes",
    author: "Stephen Fry",
    genres: ["Mythology"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8650334-L.jpg",
    year: 2018,
    pages: 480,
    blurb: "",
    rating: 0,
    spine: "#c98b3a",
    band: "#3a2418",
    ink: "#1a1414",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "mythos-213",
    title: "Mythos",
    author: "Stephen Fry",
    genres: ["Mythology"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15158055-L.jpg",
    year: 2017,
    pages: 441,
    blurb: "Here are the thrills, grandeur, and unabashed fun of the Greek myths, stylishly retold by Stephen Fry. The legendary writer, actor, and comedian breathes life into ancient tales, from Pandora's box to Prometheus's fire, and transforms the adventures of Zeus and the Olympians…",
    rating: 0,
    spine: "#3cc8c1",
    band: "#d25b2e",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "troy-222",
    title: "Troy",
    author: "Stephen Fry",
    genres: ["Mythology"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10657530-L.jpg",
    year: 2020,
    pages: 432,
    blurb: "\"A retelling of the Greek myth of the Trojan war\"--",
    rating: 0,
    spine: "#e7b82a",
    band: "#ffce2a",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Penguin",
  },
  {
    id: "wisdom-of-the-gods-for-you-and-me-95",
    title: "Wisdom of the Gods for You and Me",
    author: "Devdutt Pattanaik",
    genres: ["Mythology", "Philosophy"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12707846-L.jpg",
    year: 1200,
    pages: 1462,
    blurb: "",
    rating: 0,
    spine: "#83653c",
    band: "#96642b",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Wm. Andrus",
  },
  {
    id: "the-odyssey-11",
    title: "The Odyssey",
    author: "Homer",
    genres: ["Mythology", "Poetry & Drama"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9045853-L.jpg",
    year: 1488,
    pages: 374,
    blurb: "The Odyssey (/ˈɒdəsi/; Greek: Ὀδύσσεια, Odýsseia) is one of two major ancient Greek epic poems attributed to Homer. It is, in part, a sequel to the Iliad, the other work ascribed to Homer. The poem is fundamental to the modern Western canon, and is the second oldest extant work…",
    rating: 0,
    spine: "#dd3338",
    band: "#e01e24",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Clive",
  },
  {
    id: "the-iliad-12",
    title: "The Iliad",
    author: "Homer",
    genres: ["Mythology", "Poetry & Drama"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14546467-L.jpg",
    year: 1505,
    pages: 432,
    blurb: "This long-awaited new edition of Lattimore's Iliad is designed to bring the book into the twenty-first century—while leaving the poem as firmly rooted in ancient Greece as ever. Lattimore's elegant, fluent verses—with their memorably phrased heroic epithets and remarkable…",
    rating: 0,
    spine: "#b44527",
    band: "#cf1821",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "J. Allyn",
  },
  {
    id: "a-short-history-of-nearly-everything-2-0-13",
    title: "A Short History of Nearly Everything 2.0",
    author: "Bill Bryson",
    genres: ["Nonfiction"],
    mood: ["Adventurous", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12707846-L.jpg",
    year: 1200,
    pages: 1462,
    blurb: "",
    rating: 0,
    spine: "#83653c",
    band: "#96642b",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Wm. Andrus",
  },
  {
    id: "take-me-to-your-leader-21",
    title: "Take Me To Your Leader",
    author: "Neil deGrasse Tyson",
    genres: ["Nonfiction"],
    mood: ["Adventurous", "Thought-provoking", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/2598853-L.jpg",
    year: 2007,
    pages: 360,
    blurb: "",
    rating: 0,
    spine: "#dad751",
    band: "#ebe150",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Penguin Random House NZ",
  },
  {
    id: "the-greatest-show-on-earth-62",
    title: "The Greatest Show on Earth",
    author: "Richard Dawkins",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6257082-L.jpg",
    year: 2009,
    pages: 470,
    blurb: "",
    rating: 0,
    spine: "#030e12",
    band: "#05b7e4",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Transworld Publishers Limited",
  },
  {
    id: "universe-in-a-nutshell-63",
    title: "Universe in a Nutshell",
    author: "Stephen Hawking",
    genres: ["Nonfiction"],
    mood: ["Adventurous", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8673699-L.jpg",
    year: 2000,
    pages: 224,
    blurb: "\"One of the most influential thinkers of our time, Stephen Hawking is an intellectual icon, known not only for the adventurousness of his ideas but for the clarity and wit with which he expresses them. In this new book Hawking takes us to the cutting edge of theoretical physics,…",
    rating: 0,
    spine: "#ffffff",
    band: "#e9963d",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Odile Jacob",
  },
  {
    id: "the-theory-of-everything-64",
    title: "The Theory of Everything",
    author: "Stephen Hawking",
    genres: ["Nonfiction"],
    mood: ["Adventurous", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/942436-L.jpg",
    year: 2002,
    pages: 132,
    blurb: "",
    rating: 0,
    spine: "#100f10",
    band: "#f5a735",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Phoenix Books",
  },
  {
    id: "generative-ai-110",
    title: "Generative AI",
    author: "Harvard Business Review",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "covers/generated/generative-ai-110.jpg",
    year: 2024,
    pages: 288,
    blurb: "The play concerns a trusted general who secretly lusts for power. Encouraged by the prophecies of three witches and urged on by his ambitious wife Macbeth commits regicide. Left fearful and superstitious by this desperate act he is driven to a spiralling course of murder and…",
    rating: 0,
    spine: "#1c1c28",
    band: "#d4a83c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Harvard Business Review Press",
  },
  {
    id: "raising-mentally-strong-kids-111",
    title: "Raising Mentally Strong Kids",
    author: "Daniel G. Amen; Charles Fay",
    genres: ["Nonfiction"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14802664-L.jpg",
    year: 2024,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#ece5d4",
    band: "#f78419",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Tyndale House Publishers",
  },
  {
    id: "nexus-115",
    title: "Nexus",
    author: "Yuval Noah Harari",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14812834-L.jpg",
    year: 2024,
    pages: 544,
    blurb: "From the author of Sapiens comes the groundbreaking story of how information networks have made, and unmade, our world. For the last 100,000 years, we Sapiens have accumulated enormous power. But despite all our discoveries, inventions, and conquests, we now find ourselves in an…",
    rating: 0,
    spine: "#fbf7ed",
    band: "#e92c19",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Bompiani",
  },
  {
    id: "braiding-sweetgrass-132",
    title: "Braiding Sweetgrass",
    author: "Robin Wall Kimmerer",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7281575-L.jpg",
    year: 2013,
    pages: 409,
    blurb: "As a botanist, Robin Wall Kimmerer has been trained to ask questions of nature with the tools of science. As a member of the Citizen Potawatomi Nation, she embraces the notion that plants and animals are our oldest teachers. In *Braiding Sweetgrass*, Kimmerer brings these lenses…",
    rating: 0,
    spine: "#5a6670",
    band: "#e0d8c9",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Aufbau Verlag",
  },
  {
    id: "everything-all-at-once-137",
    title: "Everything All at Once",
    author: "Bill Nye",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9165528-L.jpg",
    year: 2017,
    pages: 360,
    blurb: "Bill Nye believes that \"everyone has an inner nerd just waiting to be awakened by the right passion. In [this book, he] will help you find yours. With his call to arms, he wants you to examine every detail of the most difficult problems that look unsolvable\"--Amazon.com.",
    rating: 0,
    spine: "#6d5f52",
    band: "#d7a243",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Rodale Books",
  },
  {
    id: "the-body-153",
    title: "The Body",
    author: "Bill Bryson",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12722746-L.jpg",
    year: 2019,
    pages: 465,
    blurb: "Bill Bryson once again proves himself to be an incomparable com- panion as he guides us through the human body—how it functions, its remarkable ability to heal itself, and (unfortunately) the ways it can fail. Full of extraordinary facts (your body made a million red blood cells…",
    rating: 0,
    spine: "#5a5a52",
    band: "#004583",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Transworld Publishers Limited",
  },
  {
    id: "down-and-out-in-paris-and-london-164",
    title: "Down and Out in Paris and London",
    author: "George Orwell",
    genres: ["Nonfiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12633283-L.jpg",
    year: 1933,
    pages: 224,
    blurb: "",
    rating: 0,
    spine: "#cd734e",
    band: "#fa6015",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Ivrea",
  },
  {
    id: "sapiens-183",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genres: ["Nonfiction"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8634250-L.jpg",
    year: 2011,
    pages: 456,
    blurb: "From a renowned historian comes a groundbreaking narrative of humanity’s creation and evolution—a #1 international bestseller—that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be “human.” One hundred thousand…",
    rating: 0,
    spine: "#fef8f6",
    band: "#e93106",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Random House Espanol",
  },
  {
    id: "cosmos-184",
    title: "Cosmos",
    author: "Carl Sagan; Ann Druyan",
    genres: ["Nonfiction"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8283901-L.jpg",
    year: 1980,
    pages: 354,
    blurb: "This book is about science in its broadest human context, how science and civilization grew up together. It is the story of our long journey of discovery and the forces and individuals who helped to shape modern science, including Democritus, Hypatia, Kepler, Newton, Huygens,…",
    rating: 0,
    spine: "#090606",
    band: "#fd3f0b",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Amfora",
  },
  {
    id: "astrophysics-for-people-in-a-hurry-186",
    title: "Astrophysics for People in a Hurry",
    author: "Neil deGrasse Tyson",
    genres: ["Nonfiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7984709-L.jpg",
    year: 2017,
    pages: 209,
    blurb: "A short book for almost all ages, it’s simply astrophysics for people in a hurry, taught by acclaimed astrophysicist Neil deGrasse Tyson. This is a must-read for anyone who wants to know how the universe works!",
    rating: 0,
    spine: "#091728",
    band: "#fabc23",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Blackstone Audiobooks",
  },
  {
    id: "a-room-of-one-s-own-24",
    title: "A Room of One's Own",
    author: "Virginia Woolf",
    genres: ["Nonfiction", "Classic Literature"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/6559057-L.jpg",
    year: 1929,
    pages: 143,
    blurb: "A Room of One's Own is an extended essay by Virginia Woolf. First published on 24 October 1929, the essay was based on a series of lectures she delivered at Newnham College and Girton College, two women's colleges at Cambridge University in October 1928. While this extended…",
    rating: 0,
    spine: "#405974",
    band: "#d29a2e",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Gyldendal",
  },
  {
    id: "84-charing-cross-road-26",
    title: "84 Charing Cross Road",
    author: "Helene Hanff",
    genres: ["Nonfiction", "Classic Literature"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/95718-L.jpg",
    year: 1970,
    pages: 120,
    blurb: "It all began with a letter inquiring about second-hand books, written by Helene Hanff in New York, and posted to a bookshop at 84, Charing Cross Road in London. As Helene's sarcastic and witty letters are responded to by the stodgy and proper bookshop employee Frank Doel, a…",
    rating: 0,
    spine: "#756a5b",
    band: "#e17f5b",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "De Harmonie",
  },
  {
    id: "the-white-album-107",
    title: "The White Album",
    author: "Joan Didion",
    genres: ["Nonfiction", "Classic Literature"],
    mood: ["Slow & Contemplative"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/4395836-L.jpg",
    year: 1979,
    pages: 222,
    blurb: "\"The White Album is a mosaic of a time, a mosaic that includes, among other bizarre artifacts and personalities, the dark journeys and impulses of the Manson Family and the Ferguson brothers, the story of Bishop James Pike, and of John Paul Getty's museum, the biker cult, the…",
    rating: 0,
    spine: "#ffffff",
    band: "#585661",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Audible Studios on Brilliance",
  },
  {
    id: "slouching-towards-bethlehem-108",
    title: "Slouching Towards Bethlehem",
    author: "Joan Didion",
    genres: ["Nonfiction", "Classic Literature"],
    mood: ["Thought-provoking", "Suspenseful"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15224908-L.jpg",
    year: 1967,
    pages: 238,
    blurb: "American novelist Joan Didion's first volume of nonfiction essays, first published in 1968, consisting of twenty works that reflect the atmosphere in America during the 1960s, especially in California.",
    rating: 0,
    spine: "#7f7372",
    band: "#904b29",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Farrar, Straus & Giroux",
  },
  {
    id: "vandargal-vendrargal-98",
    title: "Vandargal Vendrargal",
    author: "Madhan",
    genres: ["Nonfiction", "Historical Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "covers/generated/vandargal-vendrargal-98.jpg",
    year: null,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#1c1c28",
    band: "#d4a83c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "the-four-horsemen-2",
    title: "The Four Horsemen",
    author: "Richard Dawkins; Sam Harris; Daniel C. Dennett; Christopher Hitchens",
    genres: ["Philosophy"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8807297-L.jpg",
    year: 1983,
    pages: 160,
    blurb: "An interpretation of the vision which the Apostle John received on the island of Patmos foretelling the end of the world, or the Apocalypse.",
    rating: 0,
    spine: "#1d2229",
    band: "#ae925c",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "W Publishing Group",
  },
  {
    id: "outgrowing-god-185",
    title: "Outgrowing God",
    author: "Richard Dawkins",
    genres: ["Philosophy"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10031271-L.jpg",
    year: 2019,
    pages: 304,
    blurb: "",
    rating: 0,
    spine: "#293664",
    band: "#c94519",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Transworld Publishers Limited",
  },
  {
    id: "meditations-187",
    title: "Meditations",
    author: "Marcus Aurelius",
    genres: ["Philosophy"],
    mood: [],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/marcus-aurelius/meditations/george-long/downloads/cover.jpg",
    year: 2006,
    pages: 158,
    blurb: "",
    rating: 0,
    spine: "#865e4d",
    band: "#dd7f25",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Independently published",
  },
  {
    id: "east-of-eden-15",
    title: "East of Eden",
    author: "John Steinbeck",
    genres: ["Philosophy", "Classic Literature"],
    mood: ["Thought-provoking", "Bittersweet"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8757617-L.jpg",
    year: 1952,
    pages: 613,
    blurb: "Steinbeck considered East of Eden to be his masterpiece. In his journal, Journal of a Novel (often read as a companion to the novel) he notes that “this is the book I have always wanted and have worked and prayed to be able to write Set primarily in the Salinas Valley in the…",
    rating: 0,
    spine: "#c3a667",
    band: "#dfbf22",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Mandarin",
  },
  {
    id: "the-brothers-karamazov-78",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoyevsky",
    genres: ["Philosophy", "Classic Literature"],
    mood: ["Dark & Moody", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15215022-L.jpg",
    year: 1880,
    pages: 821,
    blurb: "The Brothers Karamazov, Dostoevsky’s crowning achievement, is a tale of patricide and family rivalry that embodies the moral and spiritual dissolution of an entire society (Russia in the 1870s). It created a national furor comparable only to the excitement stirred by the…",
    rating: 0,
    spine: "#1c1210",
    band: "#e7e13f",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Mission Books/eChristian, Inc.",
  },
  {
    id: "the-little-prince-146",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    genres: ["Philosophy", "Classic Literature"],
    mood: ["Heartwarming", "Thought-provoking"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/10708272-L.jpg",
    year: 1943,
    pages: 96,
    blurb: "*Le Petit Prince* est une œuvre de langue française, la plus connue d'Antoine de Saint-Exupéry. Publié en 1943 à New York simultanément à sa traduction anglaise, c'est une œuvre poétique et philosophique sous l'apparence d'un conte pour enfants. Traduit en quatre cent…",
    rating: 0,
    spine: "#9f8b69",
    band: "#b8a509",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Jāga Prakāśana",
  },
  {
    id: "the-alchemist-27",
    title: "The Alchemist",
    author: "Paulo Coelho",
    genres: ["Philosophy", "Fiction"],
    mood: ["Thought-provoking", "Slow & Contemplative", "Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14846382-L.jpg",
    year: 1988,
    pages: 197,
    blurb: "The Alchemist details the journey of a young Andalusian shepherd boy named Santiago. Santiago, believing a recurring dream to be prophetic, decides to travel to the pyramids of Egypt to find treasure. On the way, he encounters love, danger, opportunity and disaster. One of the…",
    rating: 0,
    spine: "#d69d5e",
    band: "#f49b35",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Random House Audio",
  },
  {
    id: "the-fountainhead-90",
    title: "The Fountainhead",
    author: "Ayn Rand",
    genres: ["Philosophy", "Fiction"],
    mood: ["Adventurous", "Dark & Moody", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13768762-L.jpg",
    year: 1943,
    pages: 724,
    blurb: "The Fountainhead is a 1943 novel by Ayn Rand. It was Rand's first major literary success and brought her fame and financial success. More than 6.5 million copies of the book have been sold worldwide.",
    rating: 0,
    spine: "#423126",
    band: "#e5b80f",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Easton Press",
  },
  {
    id: "jonathan-livingston-seagull-100",
    title: "Jonathan Livingston Seagull",
    author: "Richard Bach",
    genres: ["Philosophy", "Fiction"],
    mood: ["Thought-provoking", "Slow & Contemplative", "Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9381674-L.jpg",
    year: 1970,
    pages: 100,
    blurb: "",
    rating: 0,
    spine: "#f8f8f8",
    band: "#aaaaaa",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Generic",
  },
  {
    id: "atlas-shrugged-102",
    title: "Atlas Shrugged",
    author: "Ayn Rand",
    genres: ["Philosophy", "Fiction"],
    mood: ["Adventurous", "Dark & Moody", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/362277-L.jpg",
    year: 1936,
    pages: 1096,
    blurb: "",
    rating: 0,
    spine: "#736a61",
    band: "#fe594d",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Dutton",
  },
  {
    id: "love-for-imperfect-things-39",
    title: "Love for Imperfect Things",
    author: "Haemin Sunim",
    genres: ["Philosophy", "Self-Help"],
    mood: ["Cozy", "Thought-provoking", "Slow & Contemplative"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12104191-L.jpg",
    year: 2018,
    pages: 272,
    blurb: "",
    rating: 0,
    spine: "#819fab",
    band: "#ffe000",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Penguin Publishing Group",
  },
  {
    id: "the-things-you-can-see-only-when-you-slo-58",
    title: "The Things You Can See Only When You Slow Down",
    author: "Haemin Sunim",
    genres: ["Philosophy", "Self-Help"],
    mood: ["Cozy", "Slow & Contemplative"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12217703-L.jpg",
    year: 2017,
    pages: 278,
    blurb: "",
    rating: 0,
    spine: "#2b2b33",
    band: "#c9a44c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "imusti",
  },
  {
    id: "angels-in-america-68",
    title: "Angels in America",
    author: "Tony Kushner",
    genres: ["Poetry & Drama"],
    mood: ["Dark & Moody", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8871842-L.jpg",
    year: 1993,
    pages: 214,
    blurb: "Angels in America: A Gay Fantasia on National Themes is a two-part play by American playwright Tony Kushner. The work won numerous awards, including the Pulitzer Prize for Drama, the Tony Award for Best Play, and the Drama Desk Award for Outstanding Play.",
    rating: 0,
    spine: "#000407",
    band: "#36393d",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Teʼaṭron ha-Ḳameri",
  },
  {
    id: "bbc-radio-shakespeare-a-collection-of-si-124",
    title: "BBC Radio Shakespeare: A Collection of Six Tragedies",
    author: "William Shakespeare",
    genres: ["Poetry & Drama", "Classic Literature"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8281954-L.jpg",
    year: 1603,
    pages: 192,
    blurb: "In this quintessential Shakespeare tragedy, a young prince's halting pursuit of revenge for the murder of his father unfolds in a series of highly charged confrontations that have held audiences spellbound for nearly four centuries. Those fateful exchanges, and the anguished…",
    rating: 0,
    spine: "#eedeaf",
    band: "#ecd8a6",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Hachette et cie.",
  },
  {
    id: "w-m-thackeray-a-bbc-radio-drama-collecti-5",
    title: "W. M. Thackeray: A BBC Radio Drama Collection",
    author: "William Makepeace Thackeray",
    genres: ["Poetry & Drama", "Comedy"],
    mood: ["Adventurous", "Whimsical"],
    format: "audiobook",
    cover: "covers/generated/w-m-thackeray-a-bbc-radio-drama-collecti-5.jpg",
    year: null,
    pages: 114,
    blurb: "",
    rating: 0,
    spine: "#240f2a",
    band: "#e8d0b8",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "a-woman-of-no-importance-83",
    title: "A Woman of No Importance",
    author: "Oscar Wilde",
    genres: ["Poetry & Drama", "Comedy"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/oscar-wilde/a-woman-of-no-importance/downloads/cover.jpg",
    year: 1893,
    pages: 94,
    blurb: "",
    rating: 0,
    spine: "#1c2b4a",
    band: "#e0d8c9",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "B. Tauchnitz",
  },
  {
    id: "bbc-radio-shakespeare-a-collection-of-ei-123",
    title: "BBC Radio Shakespeare: A Collection of Eight Comedies",
    author: "William Shakespeare",
    genres: ["Poetry & Drama", "Comedy"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7884139-L.jpg",
    year: 1975,
    pages: 80,
    blurb: "\"American Film\" is a magazine published by The American Film Institute from 1975-1992. 10 issues were published yearly, with 166 issues in total. Originally subtitled \"The Journal of the Film and Television Arts\" the highbrow magazine initially focused on film classics but the…",
    rating: 0,
    spine: "#5f7242",
    band: "#c92100",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "American Film Institute",
  },
  {
    id: "the-blue-castle-135",
    title: "The Blue Castle",
    author: "L. M. Montgomery",
    genres: ["Romance"],
    mood: ["Cozy", "Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15125077-L.jpg",
    year: 1926,
    pages: 257,
    blurb: "Valancy Stirling is 29, unmarried, and has never been in love. Living with her overbearing mother and meddlesome aunt, she finds her only consolation in the \"forbidden\" books of John Foster and her daydreams of the Blue Castle--a place where all her dreams come true and she can…",
    rating: 0,
    spine: "#bca88d",
    band: "#c49f70",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Hesperus Press",
  },
  {
    id: "persuasion-20",
    title: "Persuasion",
    author: "Jane Austen",
    genres: ["Romance", "Classic Literature"],
    mood: ["Cozy", "Thought-provoking", "Slow & Contemplative"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/jane-austen/persuasion/downloads/cover.jpg",
    year: 1789,
    pages: 268,
    blurb: "Persuasion tells the love story of Anne Elliot and Captain Frederick Wentworth, whose sister rents Miss Elliot's father's house, after the Napoleonic Wars come to an end. The story is set in 1814. The book itself is Jane Austen's last published book, published posthumously in…",
    rating: 0,
    spine: "#483c25",
    band: "#b88414",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Xist Publishing",
  },
  {
    id: "shirley-22",
    title: "Shirley",
    author: "Charlotte Brontë",
    genres: ["Romance", "Classic Literature"],
    mood: ["Suspenseful"],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/charlotte-bronte/shirley/downloads/cover.jpg",
    year: 1800,
    pages: 600,
    blurb: "Shirley, published in 1849, was Charlotte Brontë’s second novel after Jane Eyre. Published under her pseudonym of “Currer…",
    rating: 0,
    spine: "#b8737a",
    band: "#f6efe1",
    ink: "#2b1a1a",
    finished: null,
    reading: false,
    publisher: "B. Tauchnitz",
  },
  {
    id: "beautiful-ruins-166",
    title: "Beautiful Ruins",
    author: "Jess Walter",
    genres: ["Romance", "Classic Literature"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10658056-L.jpg",
    year: 2012,
    pages: 368,
    blurb: "",
    rating: 0,
    spine: "#294543",
    band: "#9e8802",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "HarperCollins Publishers",
  },
  {
    id: "pride-and-prejudice-172",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genres: ["Romance", "Classic Literature"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/jane-austen/pride-and-prejudice/downloads/cover.jpg",
    year: 1813,
    pages: 351,
    blurb: "Pride and Prejudice is an 1813 novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments and comes to appreciate the difference between…",
    rating: 0,
    spine: "#584a2a",
    band: "#bf9342",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Yoyo USA",
  },
  {
    id: "sense-and-sensibility-173",
    title: "Sense and Sensibility",
    author: "Jane Austen",
    genres: ["Romance", "Classic Literature"],
    mood: [],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/jane-austen/sense-and-sensibility/downloads/cover.jpg",
    year: 1811,
    pages: 352,
    blurb: "When Mr. Dashwood dies, he must leave the bulk of his estate to the son by his first marriage, which leaves his second wife and three daughters (Elinor, Marianne, and Margaret) in straitened circumstances. They are taken in by a kindly cousin, but their lack of fortune affects…",
    rating: 0,
    spine: "#615138",
    band: "#ce9519",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "West Margin Press",
  },
  {
    id: "far-from-the-madding-crowd-189",
    title: "Far from the Madding Crowd",
    author: "Thomas Hardy",
    genres: ["Romance", "Classic Literature"],
    mood: [],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/thomas-hardy/far-from-the-madding-crowd/downloads/cover.jpg",
    year: 1874,
    pages: 424,
    blurb: "Independent and spirited Bathsheba Everdene has come to Weatherbury to take up her position as a farmer on the largest estate in the area. Her bold presence draws three very different suitors: the gentleman-farmer Boldwood, soldier-seducer Sergeant Troy and the devoted shepherd…",
    rating: 0,
    spine: "#27291b",
    band: "#bb8b59",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Wordsworth Edns.",
  },
  {
    id: "emma-195",
    title: "Emma",
    author: "Jane Austen",
    genres: ["Romance", "Classic Literature"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/jane-austen/emma/downloads/cover.jpg",
    year: 1815,
    pages: 457,
    blurb: "Emma, by Jane Austen, is a novel about youthful hubris and the perils of misconstrued romance. The novel was first published in December 1815. As in her other novels, Austen explores the concerns and difficulties of genteel women living in Georgian-Regency England; she also…",
    rating: 0,
    spine: "#6d3f14",
    band: "#af5b10",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Penguin USA, Inc.",
  },
  {
    id: "mansfield-park-23",
    title: "Mansfield Park",
    author: "Jane Austen",
    genres: ["Romance", "Comedy"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/14618737-L.jpg",
    year: 1814,
    pages: 443,
    blurb: "Fanny Price is born to a poor family, but is sent to her mother's rich relations to be brought up with her cousins. There she is treated as an inferior by all except her cousin Edmund, whose kindness towards her earns him her steadfast love. Fanny is quiet and obedient and does…",
    rating: 0,
    spine: "#37120a",
    band: "#92320f",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Xist Publishing",
  },
  {
    id: "bridget-jones-s-diary-117",
    title: "Bridget Jones's Diary",
    author: "Helen Fielding",
    genres: ["Romance", "Comedy"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8578467-L.jpg",
    year: 1996,
    pages: 310,
    blurb: "Bridget Jones's Diary is a 1996 novel by Helen Fielding. Written in the form of a personal diary, the novel chronicles a year in the life of Bridget Jones, a thirty-something single working woman living in London. She writes about her career, self-image, vices, family, friends,…",
    rating: 0,
    spine: "#aa8a6c",
    band: "#e0a51c",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Goldmann",
  },
  {
    id: "wuthering-heights-141",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    genres: ["Romance", "Gothic"],
    mood: ["Dark & Moody"],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/emily-bronte/wuthering-heights/downloads/cover.jpg",
    year: 1846,
    pages: 318,
    blurb: "Wuthering Heights is an 1847 novel by Emily Brontë, initially published under the pseudonym Ellis Bell. It concerns two families of the landed gentry living on the West Yorkshire moors, the Earnshaws and the Lintons, and their turbulent relationships with Earnshaw's adopted son,…",
    rating: 0,
    spine: "#4e5340",
    band: "#a87b56",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Xist Publishing",
  },
  {
    id: "the-other-bennet-sister-122",
    title: "The Other Bennet Sister",
    author: "Janice Hadlow",
    genres: ["Romance", "Historical Fiction"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9320918-L.jpg",
    year: 2020,
    pages: 368,
    blurb: "",
    rating: 0,
    spine: "#415249",
    band: "#a32d18",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Henry Holt and Company",
  },
  {
    id: "north-and-south-194",
    title: "North and South",
    author: "Elizabeth Gaskell",
    genres: ["Romance", "Historical Fiction"],
    mood: [],
    format: "physical",
    cover: "https://standardebooks.org/ebooks/elizabeth-gaskell/north-and-south/downloads/cover.jpg",
    year: 1855,
    pages: 452,
    blurb: "When her father leaves the Church in a crisis of conscience, Margaret Hale is uprooted from her comfortable home in Hampshire to move with her family to the north of England. Initially repulsed by the ugliness of her new surroundings in the industrial town of Milton, Margaret…",
    rating: 0,
    spine: "#b8737a",
    band: "#f6efe1",
    ink: "#2b1a1a",
    finished: null,
    reading: false,
    publisher: "Wordsworth Edns.",
  },
  {
    id: "shakespeare-s-sonnets-retold-73",
    title: "Shakespeare's Sonnets, Retold",
    author: "William Shakespeare; James Anthony",
    genres: ["Romance", "Poetry & Drama"],
    mood: ["Thought-provoking"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8829622-L.jpg",
    year: 1508,
    pages: 135,
    blurb: "The play concerns a trusted general who secretly lusts for power. Encouraged by the prophecies of three witches and urged on by his ambitious wife Macbeth commits regicide. Left fearful and superstitious by this desperate act he is driven to a spiralling course of murder and…",
    rating: 0,
    spine: "#ede6d7",
    band: "#faba99",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "C. Corbet",
  },
  {
    id: "a-psalm-for-the-wild-built-145",
    title: "A Psalm for the Wild-Built",
    author: "Becky Chambers",
    genres: ["Sci-Fi"],
    mood: ["Cozy", "Uplifting"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/10476616-L.jpg",
    year: null,
    pages: 147,
    blurb: "",
    rating: 0,
    spine: "#4c4f3d",
    band: "#c3770d",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "project-hail-mary-191",
    title: "Project Hail Mary",
    author: "Andy Weir",
    genres: ["Sci-Fi"],
    mood: ["Adventurous", "Fast-paced"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/11200092-L.jpg",
    year: 2021,
    pages: 496,
    blurb: "Ryland Grace is the sole survivor on a desperate, last-chance mission–and if he fails, humanity and the earth itself will perish. Except that right now, he doesn’t know that. He can’t even remember his own name, let alone the nature of his assignment or how to complete it. All…",
    rating: 0,
    spine: "#1a1c1e",
    band: "#7a8a94",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Nemira",
  },
  {
    id: "hyperion-139",
    title: "Hyperion",
    author: "Dan Simmons",
    genres: ["Sci-Fi", "Classic Literature"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13495972-L.jpg",
    year: 1989,
    pages: 481,
    blurb: "",
    rating: 0,
    spine: "#2e3442",
    band: "#01abd5",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Wydawnictwo MAG",
  },
  {
    id: "1984-181",
    title: "1984",
    author: "George Orwell",
    genres: ["Sci-Fi", "Classic Literature"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8745958-L.jpg",
    year: 1949,
    pages: 318,
    blurb: "Nineteen Eighty-Four: A Novel, often referred to as 1984, is a dystopian social science fiction novel by the English novelist George Orwell (the pen name of Eric Arthur Blair). It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his…",
    rating: 0,
    spine: "#243b3b",
    band: "#7ab8ac",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "Constable",
  },
  {
    id: "the-road-190",
    title: "The Road",
    author: "Cormac McCarthy",
    genres: ["Sci-Fi", "Classic Literature"],
    mood: ["Dark & Moody"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/198120-L.jpg",
    year: 2006,
    pages: 256,
    blurb: "Cormac McCarthy's tenth novel, The Road, is his most harrowing yet deeply personal work. Some unnamed catastrophe has scourged the world to a burnt-out cinder, inhabited by the last remnants of mankind and a very few surviving dogs and fungi. The sky is perpetually shrouded by…",
    rating: 0,
    spine: "#495560",
    band: "#4a6279",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Vintage International",
  },
  {
    id: "life-the-universe-and-everything-162",
    title: "Life, the Universe, and Everything",
    author: "Douglas Adams",
    genres: ["Sci-Fi", "Comedy"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8820112-L.jpg",
    year: 1982,
    pages: 210,
    blurb: "",
    rating: 0,
    spine: "#482e32",
    band: "#fc9935",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Arthur Barker Limited",
  },
  {
    id: "the-life-changing-magic-of-tidying-43",
    title: "The Life-Changing Magic of Tidying",
    author: "Marie Kondo",
    genres: ["Self-Help"],
    mood: ["Slow & Contemplative"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10693446-L.jpg",
    year: 2019,
    pages: 28,
    blurb: "",
    rating: 0,
    spine: "#ffffff",
    band: "#d22316",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Ten Speed Press",
  },
  {
    id: "the-little-book-of-hygge-44",
    title: "The Little Book of Hygge",
    author: "Meik Wiking",
    genres: ["Self-Help"],
    mood: ["Cozy"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10480918-L.jpg",
    year: 2016,
    pages: 288,
    blurb: "",
    rating: 0,
    spine: "#fef7ed",
    band: "#c79723",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Penguin UK",
  },
  {
    id: "tools-of-titans-46",
    title: "Tools of Titans",
    author: "Tim Ferriss",
    genres: ["Self-Help"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7902475-L.jpg",
    year: 2016,
    pages: 704,
    blurb: "Tim Ferriss, famed productivity expert and author of *The 4-Hour Work Week*, has access to some pretty high-powered individuals for his podcast. In this book, he distills the insights from their hours-long interviews, tests their methods and advice at home, and gives actionable…",
    rating: 0,
    spine: "#252526",
    band: "#e2342b",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "MT Biznes",
  },
  {
    id: "mindful-zen-habits-49",
    title: "Mindful Zen Habits",
    author: "Marc Reklau; Manuel Villa",
    genres: ["Self-Help"],
    mood: ["Thought-provoking", "Slow & Contemplative"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12489896-L.jpg",
    year: 2021,
    pages: 176,
    blurb: "",
    rating: 0,
    spine: "#cec5bc",
    band: "#f04d00",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Rupa & Company",
  },
  {
    id: "how-to-talk-so-people-will-listen-52",
    title: "How To Talk So People Will Listen",
    author: "Lizzie Waterworth",
    genres: ["Self-Help"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9157620-L.jpg",
    year: 2023,
    pages: 169,
    blurb: "",
    rating: 0,
    spine: "#171c23",
    band: "#faa91c",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Dorling Kindersley Publishing, Incorporated",
  },
  {
    id: "slow-productivity-57",
    title: "Slow Productivity",
    author: "Cal Newport",
    genres: ["Self-Help"],
    mood: ["Slow & Contemplative"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/14545976-L.jpg",
    year: 2024,
    pages: 256,
    blurb: "",
    rating: 0,
    spine: "#5a7a8a",
    band: "#f6efe1",
    ink: "#1a1414",
    finished: null,
    reading: false,
    publisher: "Penguin",
  },
  {
    id: "make-epic-money-59",
    title: "Make Epic Money",
    author: "Ankur Warikoo",
    genres: ["Self-Help"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "covers/generated/make-epic-money-59.jpg",
    year: null,
    pages: 236,
    blurb: "",
    rating: 0,
    spine: "#1c1c28",
    band: "#d4a83c",
    ink: "#f6efe1",
    finished: null,
    reading: false,
    publisher: "",
  },
  {
    id: "limitless-65",
    title: "Limitless",
    author: "Jim Kwik",
    genres: ["Self-Help"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9360116-L.jpg",
    year: 2020,
    pages: 344,
    blurb: "\"Let's say you set out to learn a new subject or skill, and you succeed. That's great. You've added to your knowledge and abilities. But it's limited to just that one thing you've learned. Now imagine that instead, the skill you learn is...how to learn. Once you know how to…",
    rating: 0,
    spine: "#0e2443",
    band: "#dce641",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Hay House",
  },
  {
    id: "make-time-70",
    title: "Make Time",
    author: "Jake Knapp; John Zeratsky",
    genres: ["Self-Help"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14179816-L.jpg",
    year: 2018,
    pages: 306,
    blurb: "Do you ever wonder where your day went? Or daydream about activities you'll get to \"someday\"? Knapp and Zeratsky share their tactics for a four-step daily framework that you can use to systematically re-design your days. Highlight, Laser, Energize, Reflect. You may not be able…",
    rating: 0,
    spine: "#f7ce3e",
    band: "#03c3fd",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Currency",
  },
  {
    id: "the-steal-like-an-artist-audio-trilogy-92",
    title: "The Steal Like an Artist Audio Trilogy",
    author: "Austin Kleon",
    genres: ["Self-Help"],
    mood: ["Whimsical", "Uplifting"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/11515539-L.jpg",
    year: 2020,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#010101",
    band: "#ffd904",
    ink: "#faf7f0",
    finished: null,
    reading: false,
    publisher: "Workman Publishing",
  },
  {
    id: "good-vibes-good-life-99",
    title: "Good Vibes, Good Life",
    author: "Vex King",
    genres: ["Self-Help"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10210924-L.jpg",
    year: 2015,
    pages: 304,
    blurb: "",
    rating: 0,
    spine: "#ffffff",
    band: "#bb9c03",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Generic",
  },
  {
    id: "dopamine-detox-116",
    title: "Dopamine Detox",
    author: "Thibaut Meurisse",
    genres: ["Self-Help"],
    mood: ["Uplifting"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15089568-L.jpg",
    year: 2021,
    pages: 74,
    blurb: "",
    rating: 0,
    spine: "#ffc70f",
    band: "#ffc900",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Independently published",
  },
  {
    id: "zen-the-art-of-simple-living-155",
    title: "Zen: The Art of Simple Living",
    author: "Shunmyo Masuno",
    genres: ["Self-Help"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14422983-L.jpg",
    year: 2019,
    pages: 224,
    blurb: "",
    rating: 0,
    spine: "#fffff7",
    band: "#0b94b1",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "Michael Joseph",
  },
  {
    id: "the-psychology-of-money-56",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    genres: ["Self-Help", "Nonfiction"],
    mood: ["Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10389354-L.jpg",
    year: 2020,
    pages: 289,
    blurb: "Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically…",
    rating: 0,
    spine: "#eef3ef",
    band: "#e3d319",
    ink: "#241f19",
    finished: null,
    reading: false,
    publisher: "no idea",
  }
];
