/* ==========================================================================
   DEFAULT TO-READ SHELF — Carol's own wishlist, seeded on first visit.

   These 7 books appeared in the source lists but never as owned/audible in
   any of them — genuinely not-yet-read: Anna Karenina, Crime and
   Punishment, In Search of Lost Time, The Magic Mountain, The Romanovs:
   1613-1918, Ulysses, White Nights.

   Seeded into the "Next in line" wishlist shelf's localStorage the first
   time someone loads the site (see loadRecommendations() in app.js).
   After that, they're regular wishlist entries — editable like anything a
   visitor recommends via "Recommend a book".
   ========================================================================== */

window.DEFAULT_RECOMMENDATIONS = [
  {
    id: "anna-karenina-0",
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/leo-tolstoy/anna-karenina/constance-garnett/downloads/cover.jpg",
    year: 1876,
    pages: 660,
    blurb: "Described by William Faulkner as the best novel ever written and by Fyodor Dostoevsky as “flawless,” Anna Karenina tells of the doomed love affair between the sensuous and rebellious Anna and the dashing officer, Count Vronsky. Tragedy unfolds as Anna rejects her passionless…",
    rating: 0,
    spine: "#635142",
    band: "#e19f7d",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Bobbs-Merrill",
  },
  {
    id: "crime-and-punishment-1",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/fyodor-dostoevsky/crime-and-punishment/constance-garnett/downloads/cover.jpg",
    year: 1866,
    pages: 520,
    blurb: "",
    rating: 0,
    spine: "#31313b",
    band: "#ad7b4b",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Yoyo USA",
  },
  {
    id: "in-search-of-lost-time-2",
    title: "In Search of Lost Time",
    author: "Marcel Proust",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/marcel-proust/in-search-of-lost-time/c-k-scott-moncrieff/downloads/cover.jpg",
    year: 1919,
    pages: 550,
    blurb: "",
    rating: 0,
    spine: "#5c2f2f",
    band: "#e0c9a6",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "VINTAGE (RAND)",
  },
  {
    id: "the-magic-mountain-3",
    title: "The Magic Mountain",
    author: "Thomas Mann",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/15010245-L.jpg",
    year: 1924,
    pages: 729,
    blurb: "One of the most influential and celebrated German works of the 20th century has been newly rendered in English by Woods, twice winner of the PEN Translation Prize. First published in 1929, Mann's novel tells the story of Hans Castorp, a modern everyman who spends seven years in…",
    rating: 0,
    spine: "#d1bfa6",
    band: "#c2ac94",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Limited Editions Club",
  },
  {
    id: "the-romanovs-1613-1918-4",
    title: "The Romanovs: 1613-1918",
    author: "Simon Sebag Montefiore",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7441421-L.jpg",
    year: 2016,
    pages: 36,
    blurb: "",
    rating: 0,
    spine: "#1184c3",
    band: "#0182ce",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "CreateSpace Independent Publishing Platform",
  },
  {
    id: "ulysses-5",
    title: "Ulysses",
    author: "James Joyce",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13136548-L.jpg",
    year: 1914,
    pages: 736,
    blurb: "Written over a seven-year period, from 1914 to 1921, this book has survived bowdlerization, legal action and controversy. The novel deals with the events of one day in Dublin, 16th June 1904, now known as \"Bloomsday\". The principal characters are Stephen Dedalus, Leopold Bloom…",
    rating: 0,
    spine: "#465d54",
    band: "#c7b08e",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Rhein-Verlag",
  },
  {
    id: "white-nights-6",
    title: "White Nights",
    author: "Fyodor Dostoevsky",
    genres: ["Fiction"],
    mood: [],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13017120-L.jpg",
    year: 1848,
    pages: 126,
    blurb: "",
    rating: 0,
    spine: "#429892",
    band: "#40a39c",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "LibriVox",
  },
  {
    id: "the-enormous-crocodile-54",
    title: "The Enormous Crocodile",
    author: "Roald Dahl; Quentin Blake",
    genres: ["Children's", "Fiction"],
    mood: ["Whimsical"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/9158796-L.jpg",
    year: 1978,
    pages: 36,
    blurb: "The enormous crocodile devises secret plans and a few clever tricks to secure his lunch only to have them foiled by his neighbors.",
    rating: 0,
    spine: "#8ac97a",
    band: "#f6efe1",
    ink: "#1a1414",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Fontein",
  },
  {
    id: "pirate-stew-114",
    title: "Pirate Stew",
    author: "Neil Gaiman; Chris Riddell",
    genres: ["Children's", "Fiction"],
    mood: ["Whimsical"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/10837704-L.jpg",
    year: 2020,
    pages: 48,
    blurb: "",
    rating: 0,
    spine: "#7ab0c9",
    band: "#e0503a",
    ink: "#1a1414",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "HarperCollins Publishers",
  },
  {
    id: "aesop-s-fables-75",
    title: "Aesop's Fables",
    author: "Aesop",
    genres: ["Classic Literature"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9627909-L.jpg",
    year: 1848,
    pages: 146,
    blurb: "",
    rating: 0,
    spine: "#44643f",
    band: "#d80702",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Books On Tape",
  },
  {
    id: "silas-marner-179",
    title: "Silas Marner",
    author: "George Eliot",
    genres: ["Classic Literature"],
    mood: ["Bittersweet"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/9286405-L.jpg",
    year: 1800,
    pages: 241,
    blurb: "Eliot's touching novel of a miser and a little child combines the charm of a fairy tale with the humor and pathos of realistic fiction. The gentle linen weaver, Silas Marner, exiles himself to the town of Raveloe after being falsely accused of a heinous theft. There he begins to…",
    rating: 0,
    spine: "#1d1d17",
    band: "#3e321e",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "B. Tauchnitz",
  },
  {
    id: "the-correspondent-126",
    title: "The Correspondent",
    author: "Virginia Evans",
    genres: ["Classic Literature", "Fiction"],
    mood: ["Bittersweet"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/15254278-L.jpg",
    year: 2025,
    pages: 360,
    blurb: "",
    rating: 0,
    spine: "#eee9e3",
    band: "#e1a122",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Penguin Books, Limited",
  },
  {
    id: "yesteryear-127",
    title: "Yesteryear",
    author: "Caro Claire Burke",
    genres: ["Classic Literature", "Fiction"],
    mood: ["Thought-provoking"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/15234864-L.jpg",
    year: 2026,
    pages: 400,
    blurb: "***'My name is Natalie Heller Mills, and I was perfect at being alive…'*** Natalie lives a traditional lifestyle – and has the social media accounts to prove it. Her charming farmhouse on her working ranch is artfully cluttered, her husband is a handsome cowboy, her homemade…",
    rating: 0,
    spine: "#8cca9e",
    band: "#efc304",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Fourth Estate",
  },
  {
    id: "middlemarch-30",
    title: "Middlemarch",
    author: "George Eliot",
    genres: ["Classic Literature", "Fiction"],
    mood: ["Slow & Contemplative"],
    format: "audiobook",
    cover: "https://standardebooks.org/ebooks/george-eliot/middlemarch/downloads/cover.jpg",
    year: 1800,
    pages: 793,
    blurb: "",
    rating: 0,
    spine: "#776d55",
    band: "#8b5e29",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "houghton mifflin company",
  },
  {
    id: "the-grapes-of-wrath-140",
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    genres: ["Classic Literature", "Historical Fiction"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8770681-L.jpg",
    year: 1939,
    pages: 544,
    blurb: "Steinbeck’s classic novel of the Great Depression is as vivid now as ever. The story focuses on a family of Oklahoma sharecroppers, farmers who work another man’s land for a share of the crops. Driven from their home by drought and poverty they take to the road in a battered old…",
    rating: 0,
    spine: "#d9cfc6",
    band: "#bb998b",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "ha-Ḳibuts ha-artsi ha-Shomer ha-tsaʻir",
  },
  {
    id: "the-paris-library-150",
    title: "The Paris Library",
    author: "Janet Skeslien Charles",
    genres: ["Classic Literature", "Historical Fiction"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/10655816-L.jpg",
    year: 2020,
    pages: 400,
    blurb: "",
    rating: 0,
    spine: "#bcb1a5",
    band: "#a86e3d",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Simon & Schuster Audio",
  },
  {
    id: "lincoln-in-the-bardo-163",
    title: "Lincoln in the Bardo",
    author: "George Saunders",
    genres: ["Classic Literature", "Historical Fiction"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/7909378-L.jpg",
    year: 2017,
    pages: 426,
    blurb: "",
    rating: 0,
    spine: "#1c2b4a",
    band: "#c9a44c",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Booket",
  },
  {
    id: "readers-digest-s-humor-in-uniform-84",
    title: "Readers Digest's Humor in Uniform",
    author: "Reader's Digest",
    genres: ["Comedy"],
    mood: ["Whimsical", "Nostalgic"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/2606776-L.jpg",
    year: 2008,
    pages: 224,
    blurb: "",
    rating: 0,
    spine: "#1f4273",
    band: "#0052af",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Reader's Digest",
  },
  {
    id: "highland-fling-204",
    title: "Highland Fling",
    author: "Nancy Mitford",
    genres: ["Comedy"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/10404648-L.jpg",
    year: 1931,
    pages: 185,
    blurb: "In Highland Fling—Nancy Mitford’s first novel, published in 1931—a set of completely incompatible and hilariously eccentric characters collide in a Scottish castle, where bright young things play pranks on their stodgy elders until the frothy plot climaxes in ghost sightings and…",
    rating: 0,
    spine: "#8b5b30",
    band: "#b01d00",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Hamilton",
  },
  {
    id: "joy-in-the-morning-210",
    title: "Joy in the Morning",
    author: "P. G. Wodehouse",
    genres: ["Comedy"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12622593-L.jpg",
    year: 1946,
    pages: 272,
    blurb: "",
    rating: 0,
    spine: "#417251",
    band: "#f61e03",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Overlook Press",
  },
  {
    id: "the-midnight-gang-50",
    title: "The Midnight Gang",
    author: "David Walliams",
    genres: ["Comedy", "Children's"],
    mood: ["Adventurous", "Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/9838897-L.jpg",
    year: 2016,
    pages: 479,
    blurb: "The Midnight Gang is a fantastic book and you will love it Hop into an adventure with some children in a hospital - I hope you like it.: ]",
    rating: 0,
    spine: "#150d30",
    band: "#ab6003",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Penguin Random House Grupo Editorial",
  },
  {
    id: "mike-and-psmith-6",
    title: "Mike and Psmith",
    author: "P. G. Wodehouse",
    genres: ["Comedy", "Classic Literature"],
    mood: ["Adventurous", "Whimsical"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/94913-L.jpg",
    year: 1935,
    pages: 190,
    blurb: "",
    rating: 0,
    spine: "#f0f1ee",
    band: "#ec3a39",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Overlook Press",
  },
  {
    id: "cold-comfort-farm-45",
    title: "Cold Comfort Farm",
    author: "Stella Gibbons",
    genres: ["Comedy", "Classic Literature"],
    mood: ["Slow & Contemplative", "Whimsical"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/13218617-L.jpg",
    year: 1932,
    pages: 240,
    blurb: "When sensible, sophisticated Flora Poste is orphaned at nineteen, she decides her only choice is to descend upon relatives in deepest Sussex. At the aptly named Cold Comfort Farm, she meets the doomed Starkadders: cousin Judith, heaving with remorse for unspoken wickedness;…",
    rating: 0,
    spine: "#f14541",
    band: "#ea2f28",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Penguin Books, Limited",
  },
  {
    id: "the-canterbury-tales-138",
    title: "The Canterbury Tales",
    author: "Geoffrey Chaucer",
    genres: ["Comedy", "Classic Literature"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/2103820-L.jpg",
    year: 1478,
    pages: 427,
    blurb: "A collection of stories written in Middle English by Geoffrey Chaucer at the end of the 14th century. The tales (mostly in verse, although some are in prose) are told as part of a story-telling contest by a group of pilgrims as they travel together on a journey from Southwark to…",
    rating: 0,
    spine: "#46454a",
    band: "#f6e40a",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Pub. for the Chaucer Society by Trübner",
  },
  {
    id: "kimu-kipi-97",
    title: "KiMu KiPi",
    author: "Madhan",
    genres: ["Comedy", "Nonfiction"],
    mood: ["Thought-provoking"],
    format: "physical",
    cover: "covers/generated/kimu-kipi-97.jpg",
    year: null,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#241c0f",
    band: "#e8b83c",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "",
  },
  {
    id: "the-arabian-nights-74",
    title: "The Arabian Nights",
    author: "Andrew Lang",
    genres: ["Fantasy"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/11716374-L.jpg",
    year: 1898,
    pages: 274,
    blurb: "In order to save her life, Sheherazade tells wonderful stories to the sultan.",
    rating: 0,
    spine: "#4c556e",
    band: "#d6bf6e",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "MobileReference",
  },
  {
    id: "the-cruel-prince-143",
    title: "The Cruel Prince",
    author: "Holly Black",
    genres: ["Fantasy"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8361789-L.jpg",
    year: 2018,
    pages: 370,
    blurb: "**GUARD YOUR MORTAL HEART.** JUDE WAS SEVEN WHEN HER PARENTS were murdered and she and her two sisters were stolen away to live in the treacherous High Court of Faerie. Ten years later, Jude wants nothing more than to belong there, despite her mortality. But many of the fey…",
    rating: 0,
    spine: "#3a1f4a",
    band: "#c9a44c",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Boekerij",
  },
  {
    id: "before-the-coffee-gets-cold-148",
    title: "Before the Coffee Gets Cold",
    author: "Toshikazu Kawaguchi",
    genres: ["Fantasy"],
    mood: ["Cozy", "Bittersweet"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12198651-L.jpg",
    year: 2015,
    pages: 240,
    blurb: "とある街の、とある喫茶店の とある座席には不思議な都市伝説があった その席に座ると、望んだとおりの時間に戻れるという ただし、そこにはめんどくさい…… 非常にめんどくさいルールがあった 1.過去に戻っても、この喫茶店を訪れた事のない者には会う事はできない 2.過去に戻って、どんな努力をしても、現実は変わらない 3.過去に戻れる席には先客がいる その席に座れるのは、その先客が席を立った時だけ 4.過去に戻っても、席を立って移動する事はできない 5.過去に戻れるのは、コーヒーをカップに注いでから、 そのコーヒーが冷めてしまうまでの間だけ…",
    rating: 0,
    spine: "#e8d8b3",
    band: "#f9b91d",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "悅知文化",
  },
  {
    id: "tales-from-the-cafe-149",
    title: "Tales from the Cafe",
    author: "Toshikazu Kawaguchi",
    genres: ["Fantasy"],
    mood: ["Cozy", "Bittersweet"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12198651-L.jpg",
    year: 2015,
    pages: 240,
    blurb: "とある街の、とある喫茶店の とある座席には不思議な都市伝説があった その席に座ると、望んだとおりの時間に戻れるという ただし、そこにはめんどくさい…… 非常にめんどくさいルールがあった 1.過去に戻っても、この喫茶店を訪れた事のない者には会う事はできない 2.過去に戻って、どんな努力をしても、現実は変わらない 3.過去に戻れる席には先客がいる その席に座れるのは、その先客が席を立った時だけ 4.過去に戻っても、席を立って移動する事はできない 5.過去に戻れるのは、コーヒーをカップに注いでから、 そのコーヒーが冷めてしまうまでの間だけ…",
    rating: 0,
    spine: "#e8d8b3",
    band: "#f9b91d",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "悅知文化",
  },
  {
    id: "the-great-hunt-151",
    title: "The Great Hunt",
    author: "Robert Jordan",
    genres: ["Fantasy"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/182352-L.jpg",
    year: 1990,
    pages: 656,
    blurb: "Now in development for TV! Since its debut in 1990, The Wheel of Time® by Robert Jordan has captivated millions of readers around the globe with its scope, originality, and compelling characters. The Wheel of Time turns and Ages come and go, leaving memories that become legend.…",
    rating: 0,
    spine: "#6a6d46",
    band: "#fb2a03",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Orbit",
  },
  {
    id: "the-dragon-reborn-152",
    title: "The Dragon Reborn",
    author: "Robert Jordan",
    genres: ["Fantasy"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/13590107-L.jpg",
    year: 1991,
    pages: 670,
    blurb: "",
    rating: 0,
    spine: "#020102",
    band: "#de8c05",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Rivages",
  },
  {
    id: "legends-lattes-169",
    title: "Legends & Lattes",
    author: "Travis Baldree",
    genres: ["Fantasy"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/15171247-L.jpg",
    year: 2024,
    pages: 656,
    blurb: "***Legends & Lattes*** After a lifetime of bounties and bloodshed, Viv is hanging up her sword for the last time. The battle-weary orc aims to start fresh, opening the first ever coffee shop in the city of Thune. But old and new rivals stand in the way of success ― not to…",
    rating: 0,
    spine: "#1f4a3a",
    band: "#c9a44c",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Tor Books",
  },
  {
    id: "the-eye-of-the-world-35",
    title: "The Eye of the World",
    author: "Robert Jordan",
    genres: ["Fantasy"],
    mood: ["Adventurous", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8452643-L.jpg",
    year: 1990,
    pages: 782,
    blurb: "",
    rating: 0,
    spine: "#8a544e",
    band: "#de4336",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Orbit",
  },
  {
    id: "the-christmas-pig-55",
    title: "The Christmas Pig",
    author: "J. K. Rowling",
    genres: ["Fantasy", "Children's"],
    mood: ["Adventurous", "Heartwarming"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12458195-L.jpg",
    year: 2021,
    pages: 288,
    blurb: "",
    rating: 0,
    spine: "#5e533b",
    band: "#e02833",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "GALLIMARD JEUNE",
  },
  {
    id: "nevermoor-4",
    title: "Nevermoor",
    author: "Jessica Townsend",
    genres: ["Fantasy", "Children's"],
    mood: ["Adventurous", "Cozy", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13550818-L.jpg",
    year: 2017,
    pages: 512,
    blurb: "A cursed girl escapes death and finds herself in a magical world-but is then tested beyond her wildest imagination Morrigan Crow is cursed. Having been born on Eventide, the unluckiest day for any child to be born, she's blamed for all local misfortunes, from hailstorms to heart…",
    rating: 0,
    spine: "#8d9386",
    band: "#be7826",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Hachette Audio",
  },
  {
    id: "the-spear-cuts-through-water-14",
    title: "The Spear Cuts Through Water",
    author: "Simon Jimenez",
    genres: ["Fantasy", "Classic Literature"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12900517-L.jpg",
    year: 2022,
    pages: 535,
    blurb: "The people suffer under the centuries-long rule of the Moon Throne. The royal family—the despotic emperor and his monstrous sons, the Three Terrors—hold the countryside in their choking grip. They bleed the land and oppress the citizens with the frightful powers they inherited…",
    rating: 0,
    spine: "#054764",
    band: "#029bfe",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Del Rey",
  },
  {
    id: "the-starless-sea-28",
    title: "The Starless Sea",
    author: "Erin Morgenstern",
    genres: ["Fantasy", "Classic Literature"],
    mood: ["Suspenseful"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/9084503-L.jpg",
    year: 2019,
    pages: 512,
    blurb: "**FAR BENEATH** the surface of the earth, upon the shores of the Starless Sea, there is a labyrinthine collection of tunnels and rooms filled with stories. The entryways that lead to this sanctuary are often hidden, sometimes on forest floors, sometimes in private homes,…",
    rating: 0,
    spine: "#3a1f4a",
    band: "#c9a44c",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Harvill Secker",
  },
  {
    id: "artemis-fowl-collection-3",
    title: "Artemis Fowl Collection",
    author: "Eoin Colfer",
    genres: ["Fantasy", "Comedy"],
    mood: ["Adventurous", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10453491-L.jpg",
    year: 2005,
    pages: 984,
    blurb: "",
    rating: 0,
    spine: "#38393b",
    band: "#9c7359",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Hyperion Books for Children",
  },
  {
    id: "the-master-and-margarita-193",
    title: "The Master and Margarita",
    author: "Mikhail Bulgakov",
    genres: ["Fantasy", "Comedy"],
    mood: ["Thought-provoking"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/15013644-L.jpg",
    year: 1966,
    pages: 436,
    blurb: "*The Master and Margarita* (Russian: Мастер и Маргарита) is a novel by Mikhail Bulgakov, written in the Soviet Union between 1928 and 1940. The story concerns a visit by the devil and his entourage to the officially atheist Soviet Union. The devil, manifested as one Professor…",
    rating: 0,
    spine: "#6f543d",
    band: "#8d1d12",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Diario El País",
  },
  {
    id: "the-sun-and-the-star-121",
    title: "The Sun and the Star",
    author: "Rick Riordan; Mark Oshiro",
    genres: ["Fantasy", "Mythology"],
    mood: ["Adventurous", "Bittersweet"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/13348151-L.jpg",
    year: 2023,
    pages: 476,
    blurb: "As the son of Hades, Nico di Angelo has been through so much, from the premature deaths of his mother and sister, to being outed against his will, to losing his friend Jason during the trials of Apollo. But there is a ray of sunshine in his life–literally: his boyfriend, Will…",
    rating: 0,
    spine: "#432e18",
    band: "#ffd603",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Intrínseca",
  },
  {
    id: "children-of-blood-and-bone-165",
    title: "Children of Blood and Bone",
    author: "Tomi Adeyemi",
    genres: ["Fantasy", "Mythology"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8572526-L.jpg",
    year: 2017,
    pages: 552,
    blurb: "Zélie Adebola remembers when the soil of Orïsha hummed with magic. Burners ignited flames, Tiders beckoned waves, and Zélie's Reaper mother summoned forth souls. But everything changed the night magic disappeared. Under the orders of a ruthless king, maji were killed, leaving…",
    rating: 0,
    spine: "#3a1f4a",
    band: "#c9a44c",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Perfection Learning Corporation",
  },
  {
    id: "origins-of-the-wheel-of-time-41",
    title: "Origins of The Wheel of Time",
    author: "Michael Livingston",
    genres: ["Fantasy", "Mythology"],
    mood: ["Adventurous", "Thought-provoking"],
    format: "audiobook",
    cover: "covers/generated/origins-of-the-wheel-of-time-41.jpg",
    year: 2022,
    pages: 256,
    blurb: "",
    rating: 0,
    spine: "#0f2e1a",
    band: "#e8c468",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Pan Macmillan",
  },
  {
    id: "neverwhere-119",
    title: "Neverwhere",
    author: "Neil Gaiman",
    genres: ["Fantasy", "Poetry & Drama"],
    mood: ["Adventurous", "Dark & Moody"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/13921349-L.jpg",
    year: 1996,
    pages: 388,
    blurb: "\"Richard Mayhew is an ordinary young man with an ordinary life and a good heart. His world is changed forever when he stops to help a girl he finds bleeding on a London sidewalk. This small kindness propels him into a dark world he never dreamed existed. He must learn to survive…",
    rating: 0,
    spine: "#460d06",
    band: "#ff800f",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Laguna",
  },
  {
    id: "fourth-wing-120",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    genres: ["Fantasy", "Romance"],
    mood: ["Adventurous", "Fast-paced"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/15235014-L.jpg",
    year: 2023,
    pages: 530,
    blurb: "Twenty-year-old Violet Sorrengail was supposed to enter the Scribe Quadrant, living a quiet life among books and history. Now, the commanding general—also known as her tough-as-talons mother—has ordered Violet to join the hundreds of candidates striving to become the elite of…",
    rating: 0,
    spine: "#e1b87d",
    band: "#e58337",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Editorial Planeta Mexicana",
  },
  {
    id: "the-invisible-life-of-addie-larue-31",
    title: "The Invisible Life of Addie LaRue",
    author: "V. E. Schwab",
    genres: ["Fantasy", "Romance"],
    mood: ["Suspenseful", "Bittersweet"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/10092261-L.jpg",
    year: 2015,
    pages: 504,
    blurb: "France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever and is cursed to be forgotten by everyone she meets. Thus begins the extraordinary life of Addie LaRue, and a dazzling adventure that will play out across centuries and continents,…",
    rating: 0,
    spine: "#232123",
    band: "#e49960",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Umbriel",
  },
  {
    id: "if-on-a-winter-s-night-a-traveler-206",
    title: "If on a Winter's Night a Traveler",
    author: "Italo Calvino",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/12007967-L.jpg",
    year: 1979,
    pages: 261,
    blurb: "",
    rating: 0,
    spine: "#f7efe9",
    band: "#d75a29",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Lester & Orpen Dennys",
  },
  {
    id: "invisible-cities-207",
    title: "Invisible Cities",
    author: "Italo Calvino",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/963147-L.jpg",
    year: 1972,
    pages: 165,
    blurb: "\"Kublai Khan does not necessarily believe everything Marco Polo says when he describes the cities visited on his expeditions, but the emperor of the Tartars does continue listening to the young Venetian with greater attention and curiosity than he shows any other messenger or…",
    rating: 0,
    spine: "#bfb4a5",
    band: "#c6b19e",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Harvest",
  },
  {
    id: "lonesome-dove-212",
    title: "Lonesome Dove",
    author: "Larry McMurtry",
    genres: ["Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/11554598-L.jpg",
    year: 1985,
    pages: 945,
    blurb: "Lonesome Dove, by Larry McMurtry, the author of Terms of Endearment, is his long-awaited masterpiece, the major noel at last of the American West as it really was. A love story, an adventure, an American epic, Lonesome Dove embraces all the West--legend and fact, heroes and…",
    rating: 0,
    spine: "#6d7862",
    band: "#f6d295",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Perfection Learning Prebound",
  },
  {
    id: "the-baron-in-the-trees-215",
    title: "The Baron in the Trees",
    author: "Italo Calvino",
    genres: ["Fiction"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/115978-L.jpg",
    year: 1957,
    pages: 275,
    blurb: "Il romanzo racconta le vicende di Cosimo di Rondò, vissuto nella seconda metà del XVIII secolo in piccolo paese della Liguria. Cosimo, per sfuggire ad un punizione, decide di salire su un albero e non scenderne mai più: si costruisce un mondo aereo dove diversi personaggi della…",
    rating: 0,
    spine: "#f9f4ee",
    band: "#e16818",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Editions du Seuil",
  },
  {
    id: "tin-man-220",
    title: "Tin Man",
    author: "Sarah Winman",
    genres: ["Fiction"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/8805153-L.jpg",
    year: 2018,
    pages: 224,
    blurb: "\"This is almost a love story. But it's not as simple as that. Ellis and Michael are twelve-year-old boys when they first become friends, and for a long time it is just the two of them, cycling the streets of Oxford, teaching themselves how to swim, discovering poetry, and…",
    rating: 0,
    spine: "#2e3a46",
    band: "#9db4a8",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Tinder Press",
  },
  {
    id: "tom-lake-221",
    title: "Tom Lake",
    author: "Ann Patchett",
    genres: ["Fiction"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/13454692-L.jpg",
    year: 2023,
    pages: 320,
    blurb: "",
    rating: 0,
    spine: "#57867f",
    band: "#0c9a88",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Harper",
  },
  {
    id: "carmilla-198",
    title: "Carmilla",
    author: "Sheridan Le Fanu",
    genres: ["Gothic"],
    mood: ["Dark & Moody"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/13995589-L.jpg",
    year: 1871,
    pages: 90,
    blurb: "",
    rating: 0,
    spine: "#161714",
    band: "#f7062b",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Livre de Poche",
  },
  {
    id: "sword-of-slaughter-160",
    title: "PS: Sword of Slaughter",
    author: "Kalki R. Krishnamurthy",
    genres: ["Historical Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "covers/generated/sword-of-slaughter-160.jpg",
    year: 2007,
    pages: 256,
    blurb: "",
    rating: 0,
    spine: "#2a1c10",
    band: "#e0c468",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Pen & Sword Books Limited",
  },
  {
    id: "whirlwinds-161",
    title: "PS: Whirlwinds",
    author: "Kalki Krishnamurthy",
    genres: ["Historical Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "covers/generated/whirlwinds-161.jpg",
    year: 2000,
    pages: 192,
    blurb: "Race to the altar! Zeke Buchanan had swept Marianne off her feet, and their two-year marriage had been perfect -- until recently.... Their physical passion was as strong as ever, but was Zeke starting to regret their impulsive wedding? The beautiful Liliana was clearly…",
    rating: 0,
    spine: "#2a1c10",
    band: "#e0c468",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Mills & Boon",
  },
  {
    id: "the-zenith-of-sacrifice-88",
    title: "PS: The Zenith of Sacrifice",
    author: "Kalki Krishnamurthy",
    genres: ["Historical Fiction", "Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "covers/generated/the-zenith-of-sacrifice-88.jpg",
    year: null,
    pages: 384,
    blurb: "",
    rating: 0,
    spine: "#2a1c10",
    band: "#e0c468",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "",
  },
  {
    id: "the-jewelled-crown-89",
    title: "PS: The Jewelled Crown",
    author: "Kalki Krishnamurthy",
    genres: ["Historical Fiction", "Fiction"],
    mood: ["Adventurous"],
    format: "physical",
    cover: "covers/generated/the-jewelled-crown-89.jpg",
    year: 1966,
    pages: 464,
    blurb: "The first instalment of Scott's Raj Quartet, about life in colonial India. A young Englishwoman, new to India and untainted by the institutionalized racism of the ruling British colonials, begins an affair with a British public school educated young Indian. When the woman is…",
    rating: 0,
    spine: "#2a1c10",
    band: "#e0c468",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "University of Chicago Press",
  },
  {
    id: "vera-wong-s-unsolicited-advice-for-murde-136",
    title: "Vera Wong’s Unsolicited Advice for Murderers",
    author: "Jesse Sutanto",
    genres: ["Mystery & Thriller"],
    mood: ["Cozy"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/13248644-L.jpg",
    year: 2023,
    pages: 368,
    blurb: "Vera Wong is a lonely little old lady—ah, lady of a certain age—who lives above her forgotten tea shop in the middle of San Francisco’s Chinatown. Despite living alone, Vera is not needy, oh no. She likes nothing more than sipping on a good cup of Wulong and doing some healthy…",
    rating: 0,
    spine: "#2295d3",
    band: "#13c1fc",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Berkley",
  },
  {
    id: "a-rage-in-harlem-167",
    title: "A Rage in Harlem",
    author: "Chester Himes",
    genres: ["Mystery & Thriller", "Classic Literature"],
    mood: [],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/10437930-L.jpg",
    year: 1957,
    pages: 159,
    blurb: "",
    rating: 0,
    spine: "#170f0c",
    band: "#824415",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Schocken Books",
  },
  {
    id: "the-tales-of-max-carrados-71",
    title: "The Tales of Max Carrados",
    author: "Ernest Bramah",
    genres: ["Mystery & Thriller", "Comedy"],
    mood: ["Suspenseful", "Whimsical"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/11146885-L.jpg",
    year: 2016,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#2e2018",
    band: "#8a2e2e",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Bolinda/Audible audio",
  },
  {
    id: "olympus-an-indian-retelling-of-the-greek-105",
    title: "Olympus: An Indian Retelling of the Greek Myths",
    author: "Devdutt Pattanaik",
    genres: ["Mythology"],
    mood: ["Whimsical"],
    format: "physical",
    cover: "covers/generated/olympus-an-indian-retelling-of-the-greek-105.jpg",
    year: null,
    pages: null,
    blurb: "",
    rating: 0,
    spine: "#2a1408",
    band: "#e8a838",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "",
  },
  {
    id: "the-aeneid-10",
    title: "The Aeneid",
    author: "Virgil",
    genres: ["Mythology", "Poetry & Drama"],
    mood: ["Adventurous"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12599332-L.jpg",
    year: 1592,
    pages: 360,
    blurb: "\"Virgil's masterpiece of Latin poetry, a lively, dramatic poem of daring and adventure, of love and loss, of devotion and death. \"",
    rating: 0,
    spine: "#392c38",
    band: "#ff9b03",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Bobbs-Merrill",
  },
  {
    id: "the-shepherd-s-life-36",
    title: "The Shepherd's Life",
    author: "James Rebanks",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking", "Slow & Contemplative"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8265736-L.jpg",
    year: 2015,
    pages: 307,
    blurb: "Some people's lives are entirely their own creations. James Rebanks' isn't. The first son of a shepherd, who was the first son of a shepherd himself, his family have lived and worked in the Lake District of Northern England for generations, further back than recorded history.…",
    rating: 0,
    spine: "#7a8a6e",
    band: "#3a2e1f",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Doubleday Canada",
  },
  {
    id: "english-pastoral-37",
    title: "English Pastoral",
    author: "James Rebanks",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking", "Slow & Contemplative"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/4519330-L.jpg",
    year: 2020,
    pages: 304,
    blurb: "",
    rating: 0,
    spine: "#5a6670",
    band: "#e0d8c9",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Penguin Books, Limited",
  },
  {
    id: "the-body-a-guide-for-occupants-38",
    title: "The Body: A Guide for Occupants",
    author: "Bill Bryson",
    genres: ["Nonfiction"],
    mood: ["Thought-provoking", "Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/12722746-L.jpg",
    year: 2019,
    pages: 465,
    blurb: "Bill Bryson once again proves himself to be an incomparable com- panion as he guides us through the human body—how it functions, its remarkable ability to heal itself, and (unfortunately) the ways it can fail. Full of extraordinary facts (your body made a million red blood cells…",
    rating: 0,
    spine: "#5a5a52",
    band: "#004583",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Transworld Publishers Limited",
  },
  {
    id: "inglorious-empire-93",
    title: "Inglorious Empire",
    author: "Shashi Tharoor",
    genres: ["Nonfiction", "Historical Fiction"],
    mood: ["Thought-provoking"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/14839187-L.jpg",
    year: 2017,
    pages: 336,
    blurb: "",
    rating: 0,
    spine: "#f4f1e1",
    band: "#c65c35",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Scribe Publications",
  },
  {
    id: "daughters-of-the-sun-96",
    title: "Daughters of the Sun",
    author: "Ira Mukhoty",
    genres: ["Nonfiction", "Historical Fiction"],
    mood: ["Thought-provoking"],
    format: "physical",
    cover: "https://covers.openlibrary.org/b/id/10837879-L.jpg",
    year: 2018,
    pages: 320,
    blurb: "",
    rating: 0,
    spine: "#5a6670",
    band: "#e0d8c9",
    ink: "#f6efe1",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Aleph Book Company",
  },
  {
    id: "bbc-radio-shakespeare-six-tragedies-17",
    title: "BBC Radio Shakespeare: Six Tragedies",
    author: "William Shakespeare",
    genres: ["Poetry & Drama"],
    mood: ["Dark & Moody", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/8281954-L.jpg",
    year: 1603,
    pages: 192,
    blurb: "In this quintessential Shakespeare tragedy, a young prince's halting pursuit of revenge for the murder of his father unfolds in a series of highly charged confrontations that have held audiences spellbound for nearly four centuries. Those fateful exchanges, and the anguished…",
    rating: 0,
    spine: "#eedeaf",
    band: "#ecd8a6",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Hachette et cie.",
  },
  {
    id: "bbc-radio-shakespeare-eight-comedies-16",
    title: "BBC Radio Shakespeare: Eight Comedies",
    author: "William Shakespeare",
    genres: ["Poetry & Drama", "Comedy"],
    mood: ["Whimsical"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7884139-L.jpg",
    year: 1975,
    pages: 80,
    blurb: "\"American Film\" is a magazine published by The American Film Institute from 1975-1992. 10 issues were published yearly, with 166 issues in total. Originally subtitled \"The Journal of the Film and Television Arts\" the highbrow magazine initially focused on film classics but the…",
    rating: 0,
    spine: "#5f7242",
    band: "#c92100",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "American Film Institute",
  },
  {
    id: "the-light-between-oceans-8",
    title: "The Light Between Oceans",
    author: "M. L. Stedman",
    genres: ["Poetry & Drama", "Historical Fiction"],
    mood: ["Suspenseful", "Bittersweet"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/7239236-L.jpg",
    year: 2012,
    pages: 345,
    blurb: "\"A novel set on a remote Australian island, where a childless couple live quietly running a lighthouse, until a boat carrying a baby washes ashore\"--",
    rating: 0,
    spine: "#bba168",
    band: "#e8d664",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Scribner",
  },
  {
    id: "brave-new-world-18",
    title: "Brave New World",
    author: "Aldous Huxley",
    genres: ["Sci-Fi"],
    mood: ["Dark & Moody", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/14887879-L.jpg",
    year: 1932,
    pages: 240,
    blurb: "Originally published in 1932, this outstanding work of literature is more crucial and relevant today than ever before. Cloning, feel-good drugs, antiaging programs, and total social control through politics, programming, and media -- has Aldous Huxley accurately predicted our…",
    rating: 0,
    spine: "#474332",
    band: "#a19403",
    ink: "#faf7f0",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Neal-Schuman publishing. New York, Toronto, London",
  },
  {
    id: "dune-42",
    title: "Dune",
    author: "Frank Herbert",
    genres: ["Sci-Fi"],
    mood: ["Adventurous", "Thought-provoking"],
    format: "audiobook",
    cover: "https://covers.openlibrary.org/b/id/13790987-L.jpg",
    year: 1965,
    pages: 607,
    blurb: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the \"spice\" melange, a drug capable of extending life and enhancing consciousness. Coveted across the…",
    rating: 0,
    spine: "#f8f8f8",
    band: "#e7b311",
    ink: "#241f19",
    recommender: "My wishlist",
    finished: "Want to read",
    publisher: "Ace Books, Inc.",
  }
];
